### ISSUE TITLE
[bug] Black background setting for transparent image 

### ISSUE THREAD

**Issue by santoshgistto** [hm21/pro_image_editor#10]
**Describe the bug**
 If image has transparent background editor setting black background color 

**Steps to Reproduce**
1. Go to crop or rotate 
2. Click on rotate 
3. save the changes

**Comment by hm21** [comment]
Thank you for reporting this issue. I've already implemented a hotfix in version `2.4.4`, which now converts images to PNG format instead of JPEG. Please let me know if the problem persists on your end, but on my end everything is currently working fine.

**Comment by santoshgistto** [comment]
Thank you @hm21  i will verify and update here
