### ISSUE TITLE
[Bug]: Emoji is not saved if state history was imported

### ISSUE THREAD

**Issue by barchinvictor** [hm21/pro_image_editor#101]
### Package Version

3.0.12

### Flutter Version

3.22.2

### Platforms

Web

### How to reproduce?

Go to https://hm21.github.io/pro_image_editor/, go to "Import and Export state history" section.  Press done. Emoji is not saved

![Screenshot 2024-06-14 at 14 35 48](https://github.com/hm21/pro_image_editor/assets/41986900/1fc7381d-f7a2-4709-87d1-2d82dfb600dd)

### Device Model (optional)

Google Chrome

**Comment by hm21** [comment]
Thank you for reporting this issue.

The problem you see here is that the emoji is not loaded or is loaded with a delay, so the background thread generates the image without the icon. 
If you want that the emoji is loaded directly, you can use a font like `GoogleFonts.notoColorEmoji()`, which I also updated in the example now.
The other option is to disable background generation in the configs, as shown below:
```dart
configs: ProImageEditorConfigs(
      imageGenerationConfigs: const ImageGeneratioConfigs(
        generateImageInBackground: false,
      ),
),
```
