### ISSUE TITLE
[Bug]: Importing history with transforms doesn't work

### ISSUE THREAD

**Issue by efalco777** [hm21/pro_image_editor#102]
### Package Version

3.0.12

### Flutter Version

3.22.2

### Platforms

iOS

### How to reproduce?

**Steps to reproduce:**

1. Open editor
2. Crop/Rotate the image
3. Save & export history (doesn't matter if it's toMap, toFile or toJson).
4. Open editor again with the same photo passing the previously exported history to **StateHistoryConfigs**

**Expected:**
Editor starts up with the image cropped/rotated.

**Actual:**
None of the previous transforms are restored.

**------------**
Issue is reproducible in the example project once we start updating the exported map.

Other properties like emojis etc. work as expected. Pretty sure the issue may be related to how the library maps the exported/imported json's.

### Logs (optional)

```sh
Package Version
3.0.12

Flutter Version
3.22.2

Platforms
iOS
```

### Device Model (optional)

iPhone 15

**Comment by hm21** [comment]
Thanks for reporting this issue.

I have updated some code which should resolve this issue in version `3.0.13`. Please let me know if you still have this problem after you update.
