### ISSUE TITLE
[Bug]: customTextStyles doesn't work

### ISSUE THREAD

**Issue by iOSyan** [hm21/pro_image_editor#111]
### Package Version

4.0.2

### Flutter Version

3.22.1

### Platforms

Android, iOS

### How to reproduce?

```dart
textEditorConfigs: TextEditorConfigs(
          enabled: true,
          canToggleTextAlign: true,
          canToggleBackgroundMode: true,
          initFontSize: 24.0,
          initialTextAlign: TextAlign.center,
          initialBackgroundColorMode: LayerBackgroundMode.background,
          customTextStyles: [
            GoogleFonts.roboto(),
            GoogleFonts.averiaLibre(),
            GoogleFonts.lato(),
            GoogleFonts.comicNeue(),
            GoogleFonts.actor(),
            GoogleFonts.odorMeanChey(),
            GoogleFonts.nabla(),
          ],
        ),

```
customTextStyles doesn't work in new version.

**Comment by hm21** [comment]
Can you also add the configuration `showSelectFontStyleBottomBar: true,` to your TextEditorConfigs and give me feedback if it works then?

**Comment by iOSyan** [comment]
It's working now. 
Since the sample code didn't include showSelectFontStyleBottomBar, I didn't know need to add it.
Thanks~

**Comment by hm21** [comment]
Yup, actually I also forgot that I added this parameter😅 However, I updated the sample code and will upload it later today.
