### ISSUE TITLE
Frost visual improvement

### ISSUE THREAD

**Issue by ember11498** [hm21/pro_image_editor#116]
### Platforms

Android, iOS

### Description

right now the frost editor looks like this:

![image](https://github.com/hm21/pro_image_editor/assets/135765222/41747e51-cedc-4fe2-b8f4-3b8e58f0da73)

I would lke to request:

The action bar at the bottom is not visible at all . Both the background of the frost and the icon color are black. the icon color has to be white to contrast with the frost. The appbar icons use Color(0xFFFFFFFF) while the actionbar (bottombar) icons use 

widget.editor.configs.icons
                              .cropRotateEditor.bottomNavBar 

which i dont know exactly what is.

even with this line:

          theme: Theme.of(context).copyWith(
              iconTheme:
                  Theme.of(context).iconTheme.copyWith(color: Colors.white)),

the icons in the actionbar are still not white.

Additionally, I would like to have the ability to set the done button with background primary color since its the most important button of the ui

### Why

Frost ui is visually hard to see

**Comment by hm21** [comment]
This seems like that you set some configuration wrong. As you can see in the example [here](https://hm21.github.io/pro_image_editor/) the icon color is white.

Anyway, the “Frosted-Glass” and “WhatsApp” designs are both built completely separate from the editor, which means you can edit every part directly by yourself. In the example you can see that there are some pre-built widgets like `FrostedGlassTextBottomBar` which only help that the user doesn't need to write all the code by himself but can still do it if he likes. So you can replace/edit any widget you don't like with your code. The pre-built widgets of the “Frosted-Glass” design can you checkout [here](https://github.com/hm21/pro_image_editor/tree/stable/lib/designs/frosted_glass).

To understand more how and in which way you can set up the editor design, you can also take a look at this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/design_examples/highly_configurable_example.dart). In that example, all configurations are very “extreme”, so you can quickly find where to set them.

> which i dont know exactly what is. even with this line: ...

The `theme` in the configs is just set global over the full editor, so everything which didn't have a fix color will take the setting from this parameter. However, the most stuff like icon colors and this stuff can you set inside `imageEditorTheme`.
