### ISSUE TITLE
[Bug]: Emoji picker bottom SafeArea

### ISSUE THREAD

**Issue by efalco777** [hm21/pro_image_editor#126]
### Package Version

^4.0.8

### Flutter Version

3.22.2

### Platforms

iOS

### How to reproduce?

Open emoji picker

**Expected**:
Bottom sheet applies SafeArea correctly from the bottom.

**Actual**:
![image](https://github.com/hm21/pro_image_editor/assets/20524697/eadf4ffa-f84f-4c12-ba11-a84d77a338f4)

### Device Model (optional)

iPhone 15

**Comment by hm21** [comment]
Okay, that's interesting. In my case this problem didn't appear and as you can see in the code [here](https://github.com/hm21/pro_image_editor/blob/319e105c241e29074791e873cd8dc239f99ffecf/lib/modules/main_editor/main_editor.dart#L1255) I enabled the option that the bottomSheet should use the safe area.
So my question is, do you set in the configs that the emojipicker bottomsheet can expand or not? And are you setting a custom config for `SystemUiOverlayStyle` anywhere in the code?

**Comment by efalco777** [comment]
I can reproduce it in the default example on iOS making no changes to the code you provided so I'm not sure what is the difference here. Could you tell me where to find the expand option? I can expand it by passing a custom editorBoxConstraintsBuilder but that doesn't fix the issue. 

I've seen you use safeArea flag when opening the bottom sheet, but looking at the emoji picker examples the usage there is putting the EmojiEditor right on the page & here you're opening it via sheet, perhaps that's why this flag doesn't work(at least not always(?)).

**Comment by hm21** [comment]
Okay I just took a closer look at it after I cleaned the build, updated every stuff from Xcode and ran it on iPhone 15 emulator I also had this issue now. Seems like when we set useSafeArea in a bottomsheet it now only works on Android and not sure but seems also on older iOS versions. Anyway, I just wrapped the EmojiPicker with the SafeArea widget now, which should resolve that issue. 
Please let me know if you still have this issue.
