### ISSUE TITLE
[Feature request] Implement Empty Canvas Option for Text-Only Designs

### ISSUE THREAD

**Issue by ikramakro** [hm21/pro_image_editor#127]
### Platforms

Android, iOS

### Description

Please include the following feature:

When a user creates a text design, the editor should initially display an empty canvas with the user's specified width and height. This will allow the user to easily edit their text, stickers, and other elements. Currently, I am experiencing issues with this functionality.

### Why

if the user only create text design then there is no option for only text design with empty canvas

**Comment by hm21** [comment]
I'm not sure if I understand you correctly, but you want to open the editor without a background image where you can add text, emojis and stickers, right? 
If so, you can follow this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/movable_background_image.dart). Just remove the `onAfterViewInit` part that initializes the editor with a sticker. Then you can add text, stickers and emojis without background. You can set the width and height in `_createTransparentImage`.

**Comment by ikramakro** [comment]
Upon opening the editor, I would like to be presented with an empty canvas.
The dimensions (height and width) and background color of this canvas
should be customizable, aligning with the standard behavior of other
editors.

**Comment by hm21** [comment]
Okay, so I understand you correctly already. As I said [here](https://github.com/hm21/pro_image_editor/issues/127#issuecomment-2182556878) this is already possible. You can follow the example which I posted in my previous answer.

**Comment by ikramakro** [comment]
thank you
------------------------------
Thank you for the clarification. I appreciate your time and patience in
explaining the process to me. I will refer to the example you provided in
your previous answer and give it a try.

Best,
Ikram Ullah
