### ISSUE TITLE
Can you remove the "enableSuggestions" or "autocorrect" in the textfield when user types in the TextEditor? That underline in the is confusing

### ISSUE THREAD

**Issue by ember11498** [hm21/pro_image_editor#132]
### Platforms

Android, iOS

### Description

Title self explanatory.

Thanks in advance.

### Why

improve visual display

**Comment by hm21** [comment]
I just released version `4.0.10` where you can now disable it in the `TextEditorConfigs` like below:
```dart
configs: ProImageEditorConfigs(
  textEditorConfigs: const TextEditorConfigs(
    enableSuggestions: false,
    autocorrect: false,
  ),
),
```
