### ISSUE TITLE
[Feature request] Highlight the selected filter item.

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#135]
### Platforms

Android, iOS

### Description

It would be nice if we could highlight the selected filter item. Please add configuration options for border width and border color for it.
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-23 at 22 03 52](https://github.com/hm21/pro_image_editor/assets/26729342/10d11683-2cd6-4977-8625-661f621d7eda)

**Comment by hm21** [comment]
This is already possible with `customWidgets` as you can see in the `WhatsApp-Example` [here](https://github.com/hm21/pro_image_editor/blob/74982d6c8e3e3d2d16e8f77821f9bcd839863c23/example/lib/pages/design_examples/whatsapp_example.dart#L304-L325). The design of the current WhatsApp filter button can you see [here](https://github.com/hm21/pro_image_editor/blob/74982d6c8e3e3d2d16e8f77821f9bcd839863c23/lib/designs/whatsapp/whatsapp_filter_button.dart).

**Comment by thanglq1** [comment]
Thank you @hm21

**Comment by thanglq1** [comment]
Hi @hm21. I'm trying to use the default FilterEditor, but it doesn't work. Please help explain.
```
filterEditor: CustomWidgetsFilterEditor(
              appBar: (filterEditor, rebuildStream) => ReactiveCustomAppbar(
                stream: rebuildStream,
                builder: (_) => _appBarFilterEditor(filterEditor),
              ),
              filterButton: (
                  filter,
                  isSelected,
                  scaleFactor,
                  onSelectFilter,
                  editorImage,
                  filterKey,
                  ) {
                return WhatsAppFilterBtn(
                  filter: filter,
                  isSelected: isSelected,
                  onSelectFilter: () {
                    onSelectFilter.call();
                    editorKey.currentState?.setState(() {});
                  },
                  editorImage: editorImage,
                  filterKey: filterKey,
                  scaleFactor: scaleFactor,
                );
              },
            ),
```

![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-24 at 20 18 52](https://github.com/hm21/pro_image_editor/assets/26729342/57ad4ef2-b8c6-455d-b599-df7573b6dad7)

**Comment by hm21** [comment]
I'm not sure what didn't work because you didn't mention it. But what I saw is that you are invoking the wrong editor. In the WhatsApp example, the filter editor is inside the main editor, but in the default example, the filter editor is standalone. You can access the filter editor like below:

```dart
filterEditor: CustomWidgetsFilterEditor(
  filterButton: (
    filter,
    isSelected,
    scaleFactor,
    onSelectFilter,
    editorImage,
    filterKey,
  ) {
    return WhatsAppFilterBtn(
      filter: filter,
      isSelected: isSelected,
      onSelectFilter: () {
        onSelectFilter.call();
        editorKey.currentState?.filterEditor.currentState
            ?.setState(() {});
      },
      editorImage: editorImage,
      filterKey: filterKey,
      scaleFactor: scaleFactor ?? 1,
    );
  },
),
```

**Comment by thanglq1** [comment]
Hi @hm21. Thank you so much. You are right. I'm using wrong editor.
