### ISSUE TITLE
[Bug]: Drawing not aligned on image.  math wrong somewhere.

### ISSUE THREAD

**Issue by sgehrman** [hm21/pro_image_editor#141]
### Package Version

4.1.0

### Flutter Version

3.22

### Platforms

Web

### How to reproduce?

editing:
![Screenshot-20240626000939-2696x1296](https://github.com/hm21/pro_image_editor/assets/287137/d8f329c0-c6e7-4af0-b036-7207cb09357c)

clicking check mark:

![Screenshot-20240626001000-2146x1867](https://github.com/hm21/pro_image_editor/assets/287137/4e740867-7ed8-4fcd-927f-4ec7c5b03415)

**Comment by hm21** [comment]
I need a sample code how I can reproduce it because in the normal case, as you can see in the [demo](https://hm21.github.io/pro_image_editor/) there is no problem. I think the problem will be the same as in this [discuss](https://github.com/hm21/pro_image_editor/discussions/51).

**Comment by sgehrman** [comment]
That works (option 2) but it looks a bit weird.

I had to add
  positionRight: 0,
              positionBottom: 0,

to get it to be on top of my centered dialog.

**Comment by hm21** [comment]
Okay, let me know if you want option 1 where you can recalculate the position by yourself depending on your situation, then I will add the feature for you.
