### ISSUE TITLE
[Bug]: Visual Artifact on PaintEditor with enabled editorIsZoomable

### ISSUE THREAD

**Issue by ynnob** [hm21/pro_image_editor#152]
### Package Version

4.2.3

### Flutter Version

3.22.2

### Platforms

Android

### How to reproduce?

When acitvating the zoom feature on the paint editor an white artifact appears. It is directly south of the "line" tool and it scrolls horizonally. Removing the editorIsZoomable functionallity also removes this artifact.

![Screenshot_20240704_142923_ZIS Dev](https://github.com/hm21/pro_image_editor/assets/34171562/8865ac9f-f550-4d85-aaae-8ae496642598)

### Example code (optional)

```Dart
paintEditorConfigs: PaintEditorConfigs(
  editorIsZoomable: true,
),
```

**Comment by hm21** [comment]
Thank you for reporting that issue with all the details. I released version `4.2.5` which should resolve this issue. Please let me know if the issue persists by you after you updated.
