### ISSUE TITLE
[Feature request] Extend PaintEditorConfigs to allow setting the default line width of paint tools

### ISSUE THREAD

**Issue by ynnob** [hm21/pro_image_editor#153]
### Platforms

Android, iOS, Web, Windows, macOS, Linux

### Description

I would like to define a default value for the line width of the tools in the paint editor.

example:
```
            paintEditorConfigs: PaintEditorConfigs(
              canChangeLineWidth: true,
              lineWidth: 2,
            ),
```

### Why

Currently the line always feels a bit clonky on most images so i would like to lower the line width as a default value.

**Comment by hm21** [comment]
You can do this inside the `PaintingEditorTheme` like below:

```dart
configs: const ProImageEditorConfigs(
    imageEditorTheme: ImageEditorTheme(
      paintingEditor: PaintingEditorTheme(
        initialStrokeWidth: 2.0,
      ),
    ),
  ),
```
