### ISSUE TITLE
[Bug]:Regression on non-full screen editor

### ISSUE THREAD

**Issue by Chris2137** [hm21/pro_image_editor#164]
### Package Version

3.0.15 / 4.2.7

### Flutter Version

3.22.0

### Platforms

Android, iOS

### How to reproduce?

Hi @hm21 , 

It's me again, (to recall memory, I'm referring to this discussion https://github.com/hm21/pro_image_editor/discussions/51), 
specifically, the problem of image got shifted up when enter editor mode happens again.
![image](https://github.com/user-attachments/assets/49ea8b25-3506-4ada-8254-beb0e701f654)

I updated my branch to latest code so you could easily reproduce, could you kindly please help to look into it again? 
https://github.com/hm21/pro_image_editor/pull/163

Many thanks,
Chris

### Example code (optional)

```Dart
#163
```

**Comment by hm21** [comment]
Hi Chris,

Thank you for reporting this issue with the example code, that helped me a lot to resolve it fast. I released version `4.2.8` which should work now. Please let me know if the issue persists by you after you updated.

**Comment by Chris2137** [comment]
It works perfect! Thanks a lot @hm21  for your quick action.
