### ISSUE TITLE
[Bug]: Returns invalid image when Done button clicked instantly the moment page loads

### ISSUE THREAD

**Issue by nirmalyohannan** [hm21/pro_image_editor#166]
### Package Version

4.2.8

### Flutter Version

3.19.6

### Platforms

Android, iOS

### How to reproduce?

When the editor screen is loaded it takes few milliseconds to load the image (100 - 800 ms). Meanwhile, the area where the image will come is blank. If image edit done button is clicked within this time, an invalid image data is returned.
It would be better if the done button is disabled until the image is displayed.

### Device Model (optional)

Nothing 2a

**Comment by hm21** [comment]
Thanks for reporting this issue. I just released version `4.2.9` which should resolve this issue.
