### ISSUE TITLE
[Bug]: The crop drag conflicts with Android navigation gestures.

### ISSUE THREAD

**Issue by francescodinova** [hm21/pro_image_editor#170]
### Package Version

4.2.5

### Flutter Version

3.22.2

### Platforms

Android

### How to reproduce?

I found the bug on a Samsung S22 device with Android 14 that has navigation gestures enabled. When I try to drag the side handles of the crop, the device recognizes the back gesture, and subsequently, the crop area no longer resizes consistently. 

### Device Model (optional)

Samsung Galaxy s22 (Android 14)

**Comment by hm21** [comment]
Okay, this problem might be a bit tricky to fix. I think the system back button from Android should still work, but the back swipe we should disable. However, I don't currently have a native android device to test it in a good way. Can you maybe fork this repository and just wrap the full [body](https://github.com/hm21/pro_image_editor/blob/db892c5e82017d2a892c86a8824371f27793c6a1/lib/modules/crop_rotate_editor/crop_rotate_editor.dart#L1864) in crop-rotate-editor inside the popscope and tell me if it works correctly?

```dart
PopScope(
      canPop: !Navigator.of(context).userGestureInProgress,
      child: /// content
```
