### ISSUE TITLE
[Feature]: Blurred shapes

### ISSUE THREAD

**Issue by christosATB** [hm21/pro_image_editor#176]
### Platforms

iOS

### Description

Is that possible to add a blurred shape functionality that will allow us to blur the background under the shape we draw? The above should apply for rectangle & ovals.

### Why

Sometimes, we want to hide sensitive information by blurring them out.

**Comment by hm21** [comment]
Hi, 

I already have it on my [roadmap](https://github.com/users/hm21/projects/7) to pixelate some areas. I had the plan to do it the same way as WhatsApp, but of course, I can also add an option that we can draw rectangles and ovals. 
However, currently I don't know a suitable solution that will have a good performance on all platforms, so this future will still need time until I have a good solution and time to program it.
