### ISSUE TITLE
[Feature request] Image Editing Options

### ISSUE THREAD

**Issue by SzymonDziak** [hm21/pro_image_editor#179]
### Platforms

Android, iOS, Web, macOS

### Description

Need image editing options for Brightness, Contrast, Saturation, Clarity, Sharpness, etc. 

### Why

Standard photo editing features

**Comment by hm21** [comment]
Hi,

Currently, I don't have enough time to add this future, but I will put it on my roadmap. 

However, for the case you want to create a PR or just create a solution for yourself, I prepared everything already. You can copy/paste the [filter-editor](https://github.com/hm21/pro_image_editor/blob/stable/lib/modules/filter_editor/filter_editor.dart) and create a new subeditor which manages this stuff. Thereafter, you replace the part where it uses the prebuilt filters and just use the raw color matrix filter, which you can see [here](https://github.com/hm21/pro_image_editor/blob/stable/lib/modules/filter_editor/utils/filter_generator/filter_addons.dart). The filter buttons you can replace with icons or images which stand for the function, like `Brightness`. 

The color matrix effects which you currently can use are brightness, contrast, saturation, colorOverlay, rgbScale, addictiveColor, grayscale, sepia, invert, hue, opacity.

For the case you want to create a PR, please keep in mind to update the [i18n](https://github.com/hm21/pro_image_editor/blob/stable/lib/models/i18n/i18n.dart), [icons](https://github.com/hm21/pro_image_editor/blob/stable/lib/models/icons/icons.dart) and [configs](https://github.com/hm21/pro_image_editor/blob/stable/lib/models/editor_configs/pro_image_editor_configs.dart) with all new stuff.
