### ISSUE TITLE
[Bug]: Saving and tapping on screen during loading results in the inability to save changes

### ISSUE THREAD

**Issue by Tomushh97** [hm21/pro_image_editor#180]
### Package Version

4.2.5

### Flutter Version

3.22.2

### Platforms

Android, iOS

### How to reproduce?

Hey, I found a bug, which is really rare, actually, but may be confusing. It's all about saving edited image, when we click on button "Done" and Saving changes state is in progress, and then if we tap on screen wherever outside that progress modal, the process stops, but if we tap on Save button again it doesn't work anymore, even if we add more changes, we can't save changes we made. We have to close process to start again.

Everything tested also on Android example:

https://github.com/user-attachments/assets/c2527ad0-530a-4b48-bc2b-d0c381d4b634

**Comment by hm21** [comment]
Thanks for reporting that issue.

May I ask, do you also have this issue in the release mode or only in the debug mode? Because the loading dialog can only be closed in the debug mode, but in the release mode should it not be possible to close it.

**Comment by Tomushh97** [comment]
When I tried it in the release mode it didn't happen

**Comment by hm21** [comment]
Okay, that's good. It's a wanted behavior in the debug-mode that we can destroy the loading-dialog even if it destroys some active tasks, so I'll close this issue.
