### ISSUE TITLE
[Bug]: Standalone editors are not properly rendering the image. Exceptions are thrown.

### ISSUE THREAD

**Issue by ember11498** [hm21/pro_image_editor#181]
### Package Version

4.3.3

### Flutter Version

3.22.3

### Platforms

Android

### How to reproduce?

Just create a simple standalone cropeditor and try any of the constructors (i tried memory and asset both are throwing the same exceptions).

Just as I am writting this post I have found the problem!! there is indeed a bug.

if i push the route as:

                        Navigator.of(context).push(
                          MaterialPageRoute(
                              builder: (context) => MyCropEditor()),
                        );
                        
it works perfectly, no issues. However, if i push with go_router package then there is a ton of exceptions

                        context.pushNamed('mycropeditor');

### Logs (optional)

```sh
I/flutter ( 4008): null
D/EGL_emulation( 4008): app_time_stats: avg=259.38ms min=2.97ms max=3936.92ms count=16

════════ Exception caught by rendering library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by scheduler library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by rendering library ═════════════════════════════════
Unsupported operation: Infinity or NaN toInt
The relevant error-causing widget was:
════════════════════════════════════════════════════════════════════════════════
```

### Example code (optional)

```Dart
class MyCropEditor extends StatefulWidget {
          const MyCropEditor({super.key});

          @override
          State<MyCropEditor> createState() => _MyCropEditorState();
        }

        class _MyCropEditorState extends State<MyCropEditor>
            with ExampleHelperState<MyCropEditor> {
          @override
          Widget build(BuildContext context) {
            return CropRotateEditor.asset(
              'assets/sun.png',
              key: editorKey,
              initConfigs: CropRotateEditorInitConfigs(
                onDone: (transformations, fitToScreenFactor) {
                  print('onDone');
                  print(transformations.toMap());
                  print('done');
                },
                onImageEditingComplete: (bytes) async {
                  print('editing complete');
                },
                onCloseEditor: () {
                  print('closing');
                  context.pop();
                },
                theme: Theme.of(context).copyWith(scaffoldBackgroundColor: Colors.red),
                //convertToUint8List: true,
                configs: ProImageEditorConfigs(
                  designMode: platformDesignMode,
                  cropRotateEditorConfigs: const CropRotateEditorConfigs(
                    //roundCropper: true,
                    canChangeAspectRatio: false,
                    initAspectRatio: 1,
                  ),
                ),
              ),
            );
          }
        }
```

### Device Model (optional)

pixel 3

**Comment by hm21** [comment]
I just tested it, but everything works fine for me, even when I use the `go_router` package you mention. However, I think the problem is that you are trying to send data with the flutter package `flutter_bloc` but your provider is below the GoRoute which can't send the data there. To test it, you can replace the editor with the code below. In case it works, the problem is as I described.
```dart
CropRotateEditor.network(
          'https://picsum.photos/id/230/2000',
          /// Other code
)
```

**Comment by ember11498** [comment]
@hm21 I was wrong earlier. even after simplifying the process by removing all bloc and that sort of stuff to try to narrow down the error i ended up with a very simple widget like:

        class MyCropEditor extends StatefulWidget {
          const MyCropEditor({super.key});

          @override
          State<MyCropEditor> createState() => _MyCropEditorState();
        }

        class _MyCropEditorState extends State<MyCropEditor> {
          final editorKey = GlobalKey<ProImageEditorState>();
          @override
          Widget build(BuildContext context) {
            return CropRotateEditor.asset(
              'assets/nature.jpg',
              key: editorKey,
              initConfigs: CropRotateEditorInitConfigs(
                onDone: (transformations, fitToScreenFactor) {
                  print('onDone');
                  print(transformations.toMap());
                  print('done');
                },
                onImageEditingComplete: (bytes) async {
                  print('editing complete');
                },
                onCloseEditor: () {
                  print('closing');
                  context.pop();
                },
                theme: Theme.of(context).copyWith(scaffoldBackgroundColor: Colors.red),
                //convertToUint8List: true,
                configs: ProImageEditorConfigs(
                  designMode: platformDesignMode,
                  cropRotateEditorConfigs: const CropRotateEditorConfigs(
                    //roundCropper: true,
                    canChangeAspectRatio: false,
                    initAspectRatio: 1,
                  ),
                ),
              ),
            );
          }
        }


I have tried with network constructor as you mentioned in your answer and it throws the exact same exceptions.

What i said earlier is incorrect, pushing the Navigator.of -> materialroutepage also doesnt work and throws the same exception as pushing with go_router.

**Can you test using pixel 3 with android 13 ("tiramisu")?**

I now tested in pixel 8 ("tiramisu") and it works. I believe there is a bug with pixel 3 tiramisu emulator

**Comment by ember11498** [comment]
@hm21 i just cleaned my Build folder and started again and I am not getting errors. Anyways, just to let you know but then I tested in a real device and there was an overflow issue of 1 pixel at the bottom

![image](https://github.com/user-attachments/assets/4ed3e98c-a211-4a09-b253-7ebcced3e8bb)

**Comment by ember11498** [comment]
@hm21 a little more context on the overflow issue but that was my mothers phone and she uses a bigger sized letter maybe that's the issue

![image](https://github.com/user-attachments/assets/c8d7045b-8b15-46eb-ba86-85791f33cb22)

**Comment by hm21** [comment]
If you want to support multiple font sizes in your application, you can replace the bottombar and appbar as you can see in this [example](https://github.com/hm21/pro_image_editor/blob/f5cdaf6ca70c82b6913482dab03e5cde2ebfd291/example/lib/pages/custom_appbar_bottombar_example.dart#L727-L801). In this case you can change that there is only an icon when your users have a bigger font size or your bottombar will grow.
