### ISSUE TITLE
[Bug]: Keyboard Issues in google_font_example

### ISSUE THREAD

**Issue by iOSyan** [hm21/pro_image_editor#182]
### Package Version

4.3.3

### Flutter Version

3.22.1

### Platforms

Android, iOS

### How to reproduce?

In the google_font_example, when you click on the already entered text again, the keyboard does not pop up.

**Comment by hm21** [comment]
I just tested it on native devices (Samsung Galaxy S10 and iPhone 10) but in my case everything works fine. Can you give more details on how to reproduce it? On which device you have this issue? Is it on native devices or only in the simulator?

**Comment by iOSyan** [comment]
I reproduced this issue on the Redmi 7 phone, and I did not encounter this problem when using the previous version 4.1.0

**Comment by hm21** [comment]
But when you click on the text, does it still show the cursor inside the text or does it also not show the cursor?

**Comment by iOSyan** [comment]
I found that the keyboard doesn't pop up easily when I click on it for the first time, but it can pop up on the second time. This issue only appears on the Redmi 7 phone, and no other testing machines have encountered it.

https://github.com/user-attachments/assets/7014eb27-d583-47a8-9de0-6b34c5c93e8a

**Comment by hm21** [comment]
That's interesting. 
I don't have a native Redmi 7 phone to reproduce the issue. However, I suspect there is a problem with the hero animation, which may not be setting the state to complete. In the code, I typically wait for the hero animation to finish before calling `focusNode.requestFocus()` to make the keyboard visible.

However, I have just released version `4.3.6`, which allows you to access the focusNode from the text editor. You can then try to manually force the keyboard to appear in the callbacks, as shown below.

```dart
return ProImageEditor.asset(
      ExampleConstants.of(context)!.demoAssetPath,
      key: editorKey,
      callbacks: ProImageEditorCallbacks(
        textEditorCallbacks: TextEditorCallbacks(
          /// onInit: () {
          ///   editorKey.currentState!.textEditor.currentState!.focusNode
          ///       .requestFocus();
          /// },
          onAfterViewInit: () {
            editorKey.currentState!.textEditor.currentState!.focusNode
                .requestFocus();
          },
        ),
```

**Comment by iOSyan** [comment]
Sorry, I've been busy these days and haven't had time to test it yet.

There is a new issue now, in the latest version 5.0.3, when running the example, an error occurs:

`../lib/widgets/extended/extended_pop_scope.dart:42:9: Error: Type 'PopInvokedWithResultCallback' not found.`

**Comment by hm21** [comment]
This is not just an issue; it involves breaking changes, as detailed in the changelog [here](https://github.com/hm21/pro_image_editor/blob/ab0ed6b5965ad2d7293dd67b77971be23ce7e39d/CHANGELOG.md?plain=1#L21-L23).

> **Breaking Changes**  
> The package now supports Flutter `3.24`, which modifies the `onPopInvoked` method.  
> A new loading dialog has been introduced as a singleton class.

This means that if you use version `>= 5.0.0`, it is mandatory to also use the latest version of Flutter.
