### ISSUE TITLE
[Bug]: Transparent background 

### ISSUE THREAD

**Issue by HeropolisDa2ny** [hm21/pro_image_editor#186]
### Package Version

4.3.3

### Flutter Version

3.22.3

### Platforms

Android, iOS, Web

### How to reproduce?

- Edit an image with a transparent background
- Use the paint editor
- Draw lines
- Save the edited picture
- The picture will have a black background

I haven't found any configuration about that but it would be great to keep a transparent background instead of replacing it by a black one. 

### Example code (optional)

```Dart
@override
  Widget build(BuildContext context) {
    return ProImageEditor.memory(
      image,
      configs: configs,
    );
  }
```

**Comment by hm21** [comment]
Do you use the default `jpg` output format, or do you set it to `png` to support transparent images? If not, could you try changing the format as shown in this [example](https://github.com/hm21/pro_image_editor/blob/a5328f28326c57fa5da497d1168979eb31cc4349/example/lib/pages/movable_background_image.dart#L311).

**Comment by HeropolisDa2ny** [comment]
Perfect it my problem is corrected with your solution 👍
