### ISSUE TITLE
[Bug]: 'PopInvokedWithResultCallback' not found.

### ISSUE THREAD

**Issue by bharaths44** [hm21/pro_image_editor#190]
### Package Version

5.0.3

### Flutter Version

3.22.3

### Platforms

iOS

### How to reproduce?

Error (Xcode): ../../.pub-cache/hosted/pub.dev/pro_image_editor-5.0.3/lib/widgets/extended/extended_pop_scope.dart:42:9: Error: Type
'PopInvokedWithResultCallback' not found.
This message is displaying when i am trying to build ipa using flutter build ipa

**Comment by hm21** [comment]
This is not just an issue; it involves breaking changes from the new flutter version, as detailed in the changelog [here](https://github.com/hm21/pro_image_editor/blob/ab0ed6b5965ad2d7293dd67b77971be23ce7e39d/CHANGELOG.md?plain=1#L21-L23).

> **Breaking Changes**  
> The package now supports Flutter `3.24`, which modifies the `onPopInvoked` method.  
> A new loading dialog has been introduced as a singleton class.

If you cannot update your package to the newest Flutter version, you can use version `4.3.6`, which is the highest version compatible with the older Flutter release.
