### ISSUE TITLE
Text displayed in single line when paste. It's working fine when type

### ISSUE THREAD

**Issue by pratik9612** [hm21/pro_image_editor#192]
### Package Version

5.1.0

### Flutter Version

3.22

### Platforms

Android, iOS

### How to reproduce?

Select multiline text from anywhere and paste on your screen which has pro_image_editer text functionality.
Then hit right icon on top right corner and pasted text will display in single line. 
It should display in multiline as copied.

**Comment by hm21** [comment]
I tested this on a native Samsung Galaxy S10 and an iPhone 12, and everything works fine. Could you please specify the exact devices on which you're experiencing this issue? And did you set any configurations on the image-editor?

**Comment by hm21** [comment]
Closed due to no response from the author.
