### ISSUE TITLE
Stop selected sticker movement functionality

### ISSUE THREAD

**Issue by pratik9612** [hm21/pro_image_editor#193]
### Package Version

5.1.0

### Flutter Version

3.22

### Platforms

Android, iOS

### How to reproduce?

When selected sticker it will be movable and rotate in entire screen. It shouldn't be move when select from list.

**Comment by hm21** [comment]
I'm sorry, but I don't quite understand your request. Are you asking whether the sticker should remain fixed in place once it's selected from the list? Do you want to prevent the user from moving the sticker after selecting it?

**Comment by hm21** [comment]
Closed due to no response from the author.
