### ISSUE TITLE
[Bug]: App crashes when we choose the result type to jpg or png format from web demo app

### ISSUE THREAD

**Issue by zahidshaikh9013** [hm21/pro_image_editor#196]
### Package Version

5.1.1

### Flutter Version

3.22.3

### Platforms

Web

### How to reproduce?

![image](https://github.com/user-attachments/assets/a84eaedf-49c3-4b9c-b925-bd2d88a92fe0)

### Device Model (optional)

Chrome browser

**Comment by hm21** [comment]
I just tried to reproduce the issue, but everything works fine on my end. Cuz you mentioned that you changed the output type to `png` (the default is `jpg`), I suspect you were using the “Generation Configurations” example, as it's the only one that directly allows you to change the output format. Did you set any other configurations that might help me reproduce the issue? If not, which version of Google Chrome are you using?

**Comment by zahidshaikh9013** [comment]
https://www.loom.com/share/c7004c42e9924b6e8164ea98d5de7edc?sid=bf37288b-2211-4b51-994e-6301f8f80985

Please check this video this is from demo webapp

https://hm21.github.io/pro_image_editor/

**Comment by zahidshaikh08** [comment]
![image](https://github.com/user-attachments/assets/cdf55493-74ca-46b1-9bf6-4aa4165a9386)

**Comment by hm21** [comment]
Okay got it, and thank you for showing detailed in the video. 

The example which you tested demonstrates the different output formats. In this example, we use a special output format `tiff` which you can see [here](https://github.com/hm21/pro_image_editor/blob/eaca6a2f3d67f6b72ed18b8bb89807a26340a401/example/lib/pages/image_format_convert_example.dart#L92). However, in the next update, I plan to include a warning to inform users that `tiff` may not be supported in their web browsers. 

FYI: As default is `jpg` the output format. For the best platform support I recommend `jpg` and `png`.
