### ISSUE TITLE
[Bug]: The image is rotate to its original position (rotate is cancelled) when crop ratio is selected

### ISSUE THREAD

**Issue by barchinvictor** [hm21/pro_image_editor#197]
### Package Version

5.1.3

### Flutter Version

3.22.3

### Platforms

Web

### How to reproduce?

Go to crop editor. Press Rotate. Then Done. Go to Crop Editor. Press Ratio. Select proportion. The image is rotate to its original position (Rotate is cancelled)

https://www.youtube.com/watch?v=Rt15G7D2Ceg

### Example code (optional)

```Dart
Example code
```

### Device Model (optional)

Google Chrome

**Comment by hm21** [comment]
This isn't an issue, it's intended behavior, as outlined [here](https://github.com/hm21/pro_image_editor/blob/ef152c4a98272d6151c47ae6e8a65a694ce4aee8/lib/modules/crop_rotate_editor/utils/crop_area_history.dart#L384-L387).

There are two reasons why I reset the crop state when the aspect ratio changes:

1. If, for example, the user rotates the image 90 degrees and then selects a 9:16 aspect ratio, it would apply the ratio flipped (16:9), which could be confusing for the user.
2. Changing the aspect ratio requires the editor to recalculate several elements, so it's easier to manage when it always starts from the default rotation. While it's technically possible to maintain the rotation, it would require additional code to implement.
