### ISSUE TITLE
[bug]  'Null' is not a subtype of type 'String' in type cast

### ISSUE THREAD

**Issue by tiltmaster** [hm21/pro_image_editor#2]
**Describe the bug**
An error appears when trying to pass emoji set as below per example documentation:

`'Null' is not a subtype of type 'String' in type cast`

```
emojiSet: [
  CategoryEmoji(
  Category.ANIMALS,
    [Emoji.fromJson({})],
   )
 ],
```

**Steps to Reproduce**
1. Open Camera
2. Navigate to ProImageEditor

**Expected Behavior**
To work as expected and open up the emoji tab

**Comment by hm21** [comment]
Thanks for the bug report. 

I've updated the example with the following code, which is more straightforward and easier to understand:
```dart
emojiSet: [
    CategoryEmoji(
      Category.ANIMALS,
      [
        Emoji(
          'emoji',
          'name',
          hasSkinTone: false,
        ),
      ],
    )
  ],
```

When using `Emoji.fromJson`, it's crucial to ensure that you provide values for all the required parameters. The method `Emoji.fromJson` works like this:
```dart
 static Emoji fromJson(Map<String, dynamic> json) {
    return Emoji(
      json['emoji'] as String,
      json['name'] as String,
      hasSkinTone:
          json['hasSkinTone'] != null ? json['hasSkinTone'] as bool : false,
    );
  }
```

**Comment by tiltmaster** [comment]
> Thanks for the bug report.
> 
> I've updated the example with the following code, which is more straightforward and easier to understand:
> 
> ```dart
> emojiSet: [
>     CategoryEmoji(
>       Category.ANIMALS,
>       [
>         Emoji(
>           'emoji',
>           'name',
>           hasSkinTone: false,
>         ),
>       ],
>     )
>   ],
> ```
> 
> When using `Emoji.fromJson`, it's crucial to ensure that you provide values for all the required parameters. The method `Emoji.fromJson` works like this:
> 
> ```dart
>  static Emoji fromJson(Map<String, dynamic> json) {
>     return Emoji(
>       json['emoji'] as String,
>       json['name'] as String,
>       hasSkinTone:
>           json['hasSkinTone'] != null ? json['hasSkinTone'] as bool : false,
>     );
>   }
> ```

Much Appreciated, using null also works by loading all emojis, but seeing a value of "null" makes it confusing as in to showing nothing. works like a charm

**Comment by tiltmaster** [comment]
Much Appreciated, using null also works by loading all emojis, but seeing a value of "null" makes it confusing as in to showing nothing. works like a charm
