### ISSUE TITLE
Feature Request: Configure only selected crop aspect ratio

### ISSUE THREAD

**Issue by rahatcse5bu** [hm21/pro_image_editor#20]
Need such options to Configure/control only selected crop aspect ratio like only 16:9 or 4:3

I mean there needs have the control-availity to disable some aspect ratio.

Also need the control to change the editing options' position as wish

**Comment by MarcioPereira155** [comment]
onImageEditingComplete: (Uint8List bytes) async { does not return the edited image, can you tell me why?

**Comment by hm21** [comment]
@rahatcse5bu Thank you for your feature request. In version 2.5.6, I have added a configuration option where you can specify which aspect ratio you want. Below is an example:
```dart
configs: ProImageEditorConfigs(
  cropRotateEditorConfigs: const CropRotateEditorConfigs(
    initAspectRatio: CropAspectRatios.ratio3_4,
    allowedAspectRatios: [
      CropAspectRatios.custom,
      CropAspectRatios.original,
      CropAspectRatios.ratio1_1,
      CropAspectRatios.ratio3_4,
      CropAspectRatios.ratio9_16,
    ],
  ),
),
```

By "control to change editing position" do you mean to order the AppBar and BottomBar differently? If yes, [here](https://github.com/hm21/pro_image_editor?tab=readme-ov-file#custom-appbar) you can see an example how to completely customize the AppBar and the same is also possible for the BottomBar with your own order and widgets.

**Comment by hm21** [comment]
@MarcioPereira155 I would appreciate it if you would open a new thread [here](https://github.com/hm21/pro_image_editor/issues/new) with your question. I can then help you to solve this problem. Please also post your code as you currently configure ProImageEditor.

**Comment by rahatcse5bu** [comment]
> @rahatcse5bu Thank you for your feature request. In version 2.5.6, I have added a configuration option where you can specify which aspect ratio you want. Below is an example:
> 
> ```dart
> configs: ProImageEditorConfigs(
>   cropRotateEditorConfigs: const CropRotateEditorConfigs(
>     initAspectRatio: CropAspectRatios.ratio3_4,
>     allowedAspectRatios: [
>       CropAspectRatios.custom,
>       CropAspectRatios.original,
>       CropAspectRatios.ratio1_1,
>       CropAspectRatios.ratio3_4,
>       CropAspectRatios.ratio9_16,
>     ],
>   ),
> ),
> ```
> 
> By "control to change editing position" do you mean to order the AppBar and BottomBar differently? If yes, [here](https://github.com/hm21/pro_image_editor?tab=readme-ov-file#custom-appbar) you can see an example how to completely customize the AppBar and the same is also possible for the BottomBar with your own order and widgets.

Lovely. for 2:3 and 3:2, will be like this: >   cropRotateEditorConfigs: const CropRotateEditorConfigs(
    initAspectRatio: CropAspectRatios.ratio2_3,
    allowedAspectRatios: [

      CropAspectRatios.ratio3__2,
      CropAspectRatios.ratio2_3,

   ],
   ),  , I mean I want to allow only 2 aspect ratio and want to disable others. and for text , is this possible like this image? 
![image](https://github.com/hm21/pro_image_editor/assets/36537475/b3e93984-baf2-4761-99cf-a83c0c1e64ac)
. Yes, I meant to order the AppBar and BottomBar differently. Thank you so much for your lovely work and reply as well

**Comment by hm21** [comment]
I see you want to use custom aspect ratios. I've changed the code in version `2.5.7` so that it's now possible to completely set custom aspect ratios. In your case, you need to configure the code like this:
```dart
 configs: ProImageEditorConfigs(
    cropRotateEditorConfigs: const CropRotateEditorConfigs(
      initAspectRatio: 3.0 / 2.0,
      aspectRatios: [
        AspectRatioItem(text: '3*2', value: 3.0 / 2.0),
        AspectRatioItem(text: '2*3', value: 2.0 / 3.0),
      ],
    ),
 ),
```
In this case, all other aspect ratios are disabled and the user has only these two options.
<br/>

It is also possible to edit the TextEditor as shown in the picture. The easiest way to do this is to create your own TextEditor widget. Below is a guide on how to do this:

1. Create your own BottomBar. You can see an example [here](https://github.com/hm21/pro_image_editor/issues/1#issuecomment-1905813898)
2. Create your own TextEditor. Copy the current TextEditor [code](https://github.com/hm21/pro_image_editor/blob/afef942edc58f3c473532f6ba013b43c7f28b08c/lib/modules/text_editor.dart) and edit it as needed.
4. Open your custom TextEditor in the BottomBar like this
````dart  
FlatIconTextButton(
        label: Text('Text', style: bottomTextStyle),
        icon: const Icon(
          Icons.text_fields,
          size: 22.0,
          color: Colors.white,
        ),
        onPressed: (){
          // TODO: open your widget. After closing the editor push the new layer to the editor.

          _editorKey.currentState.addLayer(layer);
        },
      ),
```
