### ISSUE TITLE
[Bug]: In the provided example for whatsapp how do we get the Caption text. There is no way to fetch it 

### ISSUE THREAD

**Issue by sagar1garg** [hm21/pro_image_editor#212]
### Package Version

5.1.4

### Flutter Version

3.1.7

### Platforms

Android

### How to reproduce?

 onCloseEditor does not support returning the caption text input by user in the Whatsapp example. I added the textEditingController but seems to be no way to fetch the controller value in the preview screen

**Comment by hm21** [comment]
As the name suggests, the WhatsApp example serves as a demonstration of how the implementation could look, but it will not function directly unless integrated into your code. The preview screen is designed specifically for these examples and is not applicable in a real app.
To adapt this for your own use, you will need to create a custom screen that opens after editing is complete, where the image bytes and the value from the `textController` are sent. Below is a short example what your code will look like.

```dart
callbacks: ProImageEditorCallbacks(
    onImageEditingComplete: (bytes) async {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) {
            YourPage(
              bytes: bytes,
              text: _textController.text,
            );
          },
        ),
      );
    },
```
