### ISSUE TITLE
[Feature request] Gradient background in image editor

### ISSUE THREAD

**Issue by 1041harpreet** [hm21/pro_image_editor#216]
### Platforms

Android, iOS

### Description

Can we add background gradient to selected image?. i used this to add color to background.
`imageEditorTheme: const ImageEditorTheme(
          background: Color.fromARGB(255, 54, 58, 130),
          loadingDialogTheme:
              LoadingDialogTheme(textColor: Color.fromARGB(255, 225, 255, 200)),
        ),` 
But it can take only one color, can we have gradient background property?

### Why

Like instagram, we can get color from image and then make a gradient background.

**Comment by hm21** [comment]
To set a gradient background for a captured image, a small adjustment is required. By default, the editor captures only the image area and ignores the background. As a result, depending on the output format, the background will either be black or transparent.

However, if you wish to use a gradient as the background, you can refer to the "movable-background-example." In this example, you will need to update [this section](https://github.com/hm21/pro_image_editor/blob/ea4052de35f6f9631216041d90ba754ccd3140d2/example/lib/pages/movable_background_image.dart#L182-L203) with the code provided below.

```dart
final canvas = Canvas(
  recorder,
  Rect.fromLTWH(0, 0, width.toDouble(), height.toDouble()),
);

// Define the gradient
const gradient = LinearGradient(
  colors: [Colors.blue, Colors.purple],
  begin: Alignment.topLeft,
  end: Alignment.bottomRight,
);
final paint = Paint()
  ..shader = gradient.createShader(
    Rect.fromLTWH(0, 0, width.toDouble(), height.toDouble()),
  );
canvas.drawRect(
  Rect.fromLTWH(0.0, 0.0, width.toDouble(), height.toDouble()),
  paint,
);

final picture = recorder.endRecording();
```
