### ISSUE TITLE
Add Customizable SVG Icons for IconsLayerInteraction in Edit, Remove, and RotateScale Actions

### ISSUE THREAD

**Issue by Pratik-1620** [hm21/pro_image_editor#222]
### Platforms

Android, iOS

### Description

In the IconsLayerInteraction feature, users currently interact with three main actions: Edit, Remove, and RotateScale. I propose adding an option to allow developers to customize these icons by providing their own SVG assets. This enhancement would enable developers to create a more personalized user interface that aligns with their app’s theme and design language and give them the option to completely replace the default material icons if desired.

The new feature would allow:

=> Customization of the Edit, Remove, and RotateScale icons.
=> Ability to set any SVG asset for these interactions instead of using default icons.
=> Maintaining the core functionality (edit, remove, rotate/scale) while allowing full control over the appearance.

### Why

=> Consistency in Design: By allowing custom SVG icons, developers can ensure that the design of their app remains consistent across all screens and features, improving the overall user experience.
=> Flexibility: Developers can match these icons to the app’s theme, branding, and UX guidelines, making the feature more adaptable for various use cases.
=> Enhanced User Experience: Customizing these icons can help create a more familiar interaction style for users, potentially increasing ease of use and engagement.
This feature would empower developers with additional flexibility while keeping the integrity of the IconsLayerInteraction intact.
=> Reduce app size: Developer can remove material icons completely if they are not using that help them to reduce the final build size of apk/ipa

**Comment by hm21** [comment]
Hi,

Thank you for your feature request.

By default, Flutter does not support displaying `SVG` images. The only option is to use external packages like [flutter_svg](https://pub.dev/packages/flutter_svg) to render `SVG` images.

However, the recommended way in Flutter is that you create a custom icon font, allowing you to use your icons. If your icons are only available as SVGs, you can convert them [here](https://www.fluttericon.com/) into a font, which can then be used as icons. If you're unfamiliar with adding custom fonts, you can refer to [this article](https://docs.flutter.dev/cookbook/design/fonts), which explains the process in detail.

If you would prefer not to use an icon font for your SVG icons, I can add that feature request to my to-do list. However, it will take some time to implement, as I have a few higher-priority tasks at the moment. Alternatively, if you need this feature sooner, you are welcome to create a pull request.

**Comment by Pratik-1620** [comment]
Hey @hm21 

Thanks for the prompt response.

I am using flutter_svg in my application. The main reason behind this change is to avoid adding material icons into the project. My client prefers that the app size be as small as possible. We are using very few icons in the app, so I am replacing all the icons with SVGs from your package. I have replaced all except the three I mentioned, as those are not set using the Icons class.

**Comment by hm21** [comment]
Just to confirm my understanding, you're replacing every icon except these three with an SVG image from the `flutter_svg` package, rather than using your own font, correct? 
I'm asking because you mentioned `IconsLayerInteraction` and said, "those are not set using the Icons class" which left me a bit uncertain about what you did exactly. The `ImageEditorIcons` class only allows adding `IconData`, not widgets like `SvgPicture`, so I want to ensure we're on the same page. 

Do you maybe use `ImageEditorCustomWidgets` to replace every other icon?

**Comment by Pratik-1620** [comment]
Here I have attached what I did to replace the other icons with svg. Refer screenshot 1. Now When I am trying to change for the other three (highlighted in screenshot 2) it gives error.
<img width="583" alt="Screenshot 2024-09-19 at 11 01 56 AM" src="https://github.com/user-attachments/assets/b720184c-8fee-472f-a5e3-edd22b77d284">

<img width="440" alt="Screenshot 2024-09-19 at 10 57 42 AM" src="https://github.com/user-attachments/assets/284e0c4c-76a8-4cb4-9a8d-ad2b97400f1c">

**Comment by hm21** [comment]
Okay, got it, you used before custom widgets to replace it. I just released version `5.3.0` which allows you also to replace these icons with custom widgets. You can view an example of how to implement this feature [here](https://github.com/hm21/pro_image_editor/blob/d3d94bb34a2a2a2cfe345d252d619e24d8ed2260/example/lib/pages/custom_appbar_bottombar_example.dart#L199-L312).
