### ISSUE TITLE
[Bug]: WARNING: Falling back to CPU-only rendering. Failed to initialize WebGL context.

### ISSUE THREAD

**Issue by RahajulAminRaju** [hm21/pro_image_editor#223]
### Package Version

5.2.2

### Flutter Version

Flutter 3.26.0-0.1.pre • channel beta

### Platforms

Web

### How to reproduce?

bugs: WARNING: Falling back to CPU-only rendering. Failed to initialize WebGL context.
bytes data: image_data: []

I found the bug onImageEditingComplete: (bytes) async {}.
here, no byte data I'm getting. how can I solve this or this is a package issue?

this is happening only in web. android is okay.

**Comment by hm21** [comment]
Could you share your current code with the image editor so we can try to reproduce the issue? It would also be helpful to know which web browser you're experiencing this problem on. Have you already tried using the [example code](https://github.com/hm21/pro_image_editor/tree/stable/example/lib/pages)? If so, do you encounter the same issue when you copy and paste sections of it into your project?

**Comment by RahajulAminRaju** [comment]
I got the issue. It was because of  imageGenerationConfigs: ImageGenerationConfigs() configuration. I've set ratio very large that's why it was happening.
