### ISSUE TITLE
[Feature request] add sliders to adjust the brightness contrast and temperature ...! 

### ISSUE THREAD

**Issue by dev-basit-seerox** [hm21/pro_image_editor#224]
### Platforms

Android, iOS, Web, Windows, macOS, Linux

### Description

add sliders to adjust the brightness contrast and temperature ...! I'm trying to add them but i'm facing errors please add this

**Comment by hm21** [comment]
I just answered the same question [here](https://github.com/hm21/pro_image_editor/discussions/226#discussioncomment-10700931)
