### ISSUE TITLE
[Bug]: Export and Import issue.  After import content are getting cropped and size changed.

### ISSUE THREAD

**Issue by RahajulAminRaju** [hm21/pro_image_editor#227]
### Package Version

5.2.2

### Flutter Version

3.26.0-0.1.pre • channel beta

### Platforms

Android, Web

### How to reproduce?

First off all when i export it was like this:
![20240922-090816](https://github.com/user-attachments/assets/1b504ca6-08c2-48c0-a178-ee76c8299ac7)

but after import the image is getting cropped and sometime the image size/scale is getting bigger than what i saved.
![20240922-090821](https://github.com/user-attachments/assets/0bc786a5-91d3-4acd-8e6b-a6c4e1b97af5)

this was my code for export(I tried both json and map export but got save issue):
IconButton(
                                onPressed: () async {
                                  // Assuming `ExportEditorConfigs` and `editor.exportStateHistory` are predefined
                                  var history =
                                  await editor.exportStateHistory(

                                    configs: const ExportEditorConfigs(

                                      // configs...
                                      exportPainting: true,
                                      exportText: true,
                                      exportCropRotate: false,
                                      exportFilter: true,
                                      exportEmoji: true,
                                      exportSticker: true,

                                      historySpan:
                                      ExportHistorySpan.current,

                                    ),

                                  );

                                  // // Convert history to JSON
                                  // var _historyJson =
                                  // await history.toJson();

                                  historyMapData = await history.toMap();

                                  // setState(() async {
                                  //   // historyJson = _historyJson;
                                  // });
                                  
                                },
                                icon: const Icon(
                                  Icons.send_to_mobile_outlined,
                                  color: Colors.white,
                                ),
                              ),
                              
                              **this is my import code:**
                              stateHistoryConfigs: StateHistoryConfigs(
              initStateHistory: ImportStateHistory.fromMap(
                // historyJson,
                historyMapData,

                configs: const ImportEditorConfigs(
                   recalculateSizeAndPosition: true,
                    // mergeMode: ImportEditorMergeMode.replace

                ),
              ),
            ),

**Comment by hm21** [comment]
When importing/exporting stickers in your editor, it is important to set the `boxfit` property on your images to `cover` rather than `contain`. This step is essential because it allows the editor to capture the images correctly without cutting any part of it.

You can try this [example](https://github.com/hm21/pro_image_editor/blob/ca0d1749d69b66144abaca5a4b667f5ca0081388/example/lib/pages/stickers_example.dart#L105-L158) to see if it works for you. If it doesn't work, please let me know it.

**Comment by RahajulAminRaju** [comment]
That didn't solve my problem. I've solve this like this way: 

I have to save twice then i saved correctly. Firstly I've add all images for making a template. then export those > close the editor> open again and import the exported element > reedit and resize them > export again > now the issue is solved. if i import again it is save as i exported.

Thanks.

**Comment by hm21** [comment]
It should be possible to export it correctly. Could you share the full code you're using for the image editor, including how you're handling the import/export process? I'd like to take a look at it to better understand the issue.
