### ISSUE TITLE
[Feature request] Pinch to zoom/zoom out image

### ISSUE THREAD

**Issue by Thesergiolg99** [hm21/pro_image_editor#234]
### Platforms

Android, iOS

### Description

Would be nice having the ability from the main editor to resize the image like on instagram with the fingers, so that it keeps the 9:16 format of the image to create stories and if the image isnt of that format, that you can resize it with the fingers.

### Why

Is very important to have this funcitonality for a nice user experiencie in a social media platform

**Comment by hm21** [comment]
To achieve this, you will need to use the image as a layer. You can refer to this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/movable_background_image.dart), which demonstrates how to enable image movement and resizing.

**Comment by Thesergiolg99** [comment]
Oh! Okay will definetely take a look, many thanks!!

**Comment by Thesergiolg99** [comment]
Hi @hm21 So much appreciated for you help, ive implemented you example and managed to get it working like a charm. I have just one question:

When the editor opens with an image, will be like this:
<img width="323" alt="Captura de pantalla 2024-10-03 a las 13 30 20" src="https://github.com/user-attachments/assets/8fa356a9-8747-4d30-a96a-f9635da1506d">

But when i try to rescale the image layer or the text layer, the ui changes and its not exact as it was before, example:


https://github.com/user-attachments/assets/a0dc2cac-2991-4843-9042-27cfd1a51e4f

Like if it wasnt precise, why would this happen.

Thanks for all your help!

**Comment by hm21** [comment]
Could you post your code from the image editor so I can take a look at it??

**Comment by Thesergiolg99** [comment]
> Could you post your code from the image editor so I can take a look at it??

Hi!, it was a proggramming error by me hehe, redid it again copying parts of your code and now its all as it should be. So many thanks!!
