### ISSUE TITLE
Video editing

### ISSUE THREAD

**Issue by Thesergiolg99** [hm21/pro_image_editor#235]
### Platforms

Android, iOS

### Description

Would be a game changer to let the editor upload a video, like instagram, so its inserted as a layer same as its done with te image. Would love to help if i can with anything.

### Why

Now a days social medias are based on video as well as images.

**Comment by hm21** [comment]
That would be a great feature, but implementing it will take a significant amount of time, especially for the generation aspect. In my current projects, I do not require this feature, so I have no plans to implement it. However, for anyone who wishes to implement it and want to create a PR, I will explain below which parts will need to be modified.


## Layer 
- Create a new layer class, possibly named `VideoLayerData`, in the following file: [layer.dart](https://github.com/hm21/pro_image_editor/blob/stable/lib/models/layer/layer.dart).
- Update the layer widget to include the new video layer in this file: [layer_widget.dart](https://github.com/hm21/pro_image_editor/blob/stable/lib/widgets/layer_widget.dart). I suggest using the [media_kit](https://pub.dev/packages/media_kit) package, as it supports video playback across all platforms, making it the easiest option.


## Generation
- To capture the final video, it will be necessary to write entirely new logic in the [content_recorder](https://github.com/hm21/pro_image_editor/tree/stable/lib/utils/content_recorder.dart) to capture only the video. Similar to how the photo capture process is handled, it will be essential to use multi-threading. This means using isolates on Dart native platforms and setting up a web worker for Dart-web.
- Update the [output_formats](https://github.com/hm21/pro_image_editor/blob/stable/lib/models/editor_configs/image_generation_configs/output_formats.dart) file with the possible formats. At a minimum, it should support `MP4` and `GIF`. If you want to implement additional formats, `MOV`, `AVI`, and `MKV` could also be useful.
- Implement the logic to apply filters, paintings, and other effects.
- It should also support video cropping, allowing users to trim the video length.
- Consider the possibility of running background threads to apply changes directly, similar to how it's currently done in the photo editor.

## Import/ Export
- The editor currently supports [importing/exporting](https://github.com/hm21/pro_image_editor/tree/stable/lib/models/import_export) everything as a `JSON` file. It may be necessary to add parameters for features like cropped duration.

## Various
- Update the [changelog](https://github.com/hm21/pro_image_editor/blob/stable/CHANGELOG.md) file.
- Update the [readme](https://github.com/hm21/pro_image_editor/blob/stable/README.md) file.
