### ISSUE TITLE
[Bug]: PaintingEditor's onImageEditingComplete returns the previously "undo/undone" element instead of the latest drawing

### ISSUE THREAD

**Issue by darielkurt** [hm21/pro_image_editor#239]
### Package Version

5.4.1

### Flutter Version

3.24.0

### Platforms

Android, iOS, Web

### How to reproduce?

Hi, thanks for this awesome package. However, I encountered an issue with the `PaintingEditor`

I replicated this on Android and iOS when we used `PaintingEditor.memory` on our project. Checked on the demo website if it is actually an issue and it exists on the demo web app.

Steps:

Web
1. Go to the [demo website](https://hm21.github.io/pro_image_editor/)
2. Click "Signature or Drawing"
3. Click either "Signature" or "Drawing"
4. Draw anything (ex. circle)
5. Click "Undo"
6. Draw anything again (ex. a line)
7. Click the check button
8. Notice that the result is the one drawn previously (the one you draw on Step 4 above, circle)

**Comment by hm21** [comment]
Thanks for reporting that issue with detailed reproduction steps. I've just released version `5.4.2`, which should resolve it.

**Comment by darielkurt** [comment]
> Thanks for reporting that issue with detailed reproduction steps. I've just released version `5.4.2`, which should resolve it.

Thank you for your quick response. I hope to contribute to this package someday.
