### ISSUE TITLE
[Feature request] make the editing widgets positionable

### ISSUE THREAD

**Issue by B-O-B-G-I-T** [hm21/pro_image_editor#241]
### Platforms

Android, iOS, Web

### Description

A new feature allows developers to freely position and arrange widgets anywhere on the screen using custom (x, y) coordinates. It provides full control over the layout of UI elements, without being constrained by standard layouts (Column, Row, etc.). Widgets can be moved, resized, or dynamically adjusted as needed.

### Why

This function could help to make a better interface finally to the taste of the application

**Comment by hm21** [comment]
It is possible to add your own widgets at fixed or custom positions by using `customWidgets` in the configuration settings. Below is an example of how to do this.


```dart
configs: ProImageEditorConfigs(
    customWidgets: ImageEditorCustomWidgets(
      mainEditor: CustomWidgetsMainEditor(
        bodyItems: (editor, rebuildStream) {
          return [
            ReactiveCustomWidget(
              stream: rebuildStream,
              builder: (_) =>
                  editor.selectedLayerIndex >= 0 || editor.isSubEditorOpen
                      ? const SizedBox.shrink()
                      : Positioned(
                          bottom: 20,
                          left: 0,
                          child: Container(
                            decoration: BoxDecoration(
                              color: Colors.lightBlue.shade200,
                              borderRadius: const BorderRadius.only(
                                topRight: Radius.circular(100),
                                bottomRight: Radius.circular(100),
                              ),
                            ),
                            child: IconButton(
                              onPressed: () {
                               /// Some Interaction
                              },
                              icon: const Icon(
                                Icons.reorder,
                                color: Colors.white,
                              ),
                            ),
                          ),
                        ),
            ),
          ];
        },
      ),
    ),
  ),
```

**Comment by B-O-B-G-I-T** [comment]
Oh, sorry, I now understand a bit better how your package is structured.

**Comment by hm21** [comment]
You can also check out the [examples](https://github.com/hm21/pro_image_editor/tree/stable/example/lib/pages), which might be helpful. These examples are the same ones used in the [web demo](https://hm21.github.io/pro_image_editor/).
