### ISSUE TITLE
[Question] How to add frames ? 

### ISSUE THREAD

**Issue by eserdeiro** [hm21/pro_image_editor#245]
I would like to implement a feature that allows adding customizable frames to a photo, similar to the examples in the attached image (with balloons, banners, and celebration themes). How can I achieve this in my project?

Some key functionalities I am looking for:

Ability to choose from different frame designs.
Option for the user to upload their photo after selecting the frame.
Option to export the final image with the applied frame.

Any guidance or examples would be appreciated.
![Captura de pantalla 2024-10-16 a la(s) 1 10 33 p  m](https://github.com/user-attachments/assets/2c9af1cd-0f78-4091-88fa-02732b371b2a)

**Comment by hm21** [comment]
Hi,

I’ll move your questions from the Issues tab to the Discussions tab, as I prefer having questions there. It’s better for Q&A, making it easier for other users to find answers to similar questions.


Anyway, that's an interesting feature! To provide the best solution, I have a few questions:

1. Should the frames have a fixed position, or should users be able to move and resize them?
2. Do users need to perform other actions, like painting or cropping the image?
3. Would it make more sense for users to upload the image first and then select the frame, so they can immediately see how it looks?
