### ISSUE TITLE
[Bug]: Escape key throw error when context menu is open

### ISSUE THREAD

**Issue by ed2220** [hm21/pro_image_editor#260]
### Package Version

6.1.2

### Flutter Version

3.24.3

### Platforms

Windows

### How to reproduce?

When I add any layer in the main editor and right-click on one of them, the option to remove appears. If I press Esc while this option is available, the error below occurs.

![image](https://github.com/user-attachments/assets/2ca5fe75-5026-4773-97d0-2c673d09f9b6)

![image](https://github.com/user-attachments/assets/bb1125e4-f247-400e-8fa9-7741f3abc607)

I noticed that in the web example of the editor, pressing Esc does nothing; only holding it closes the option to remove. Any idea what might be causing this? Is there a way for me to disable Esc?

**Comment by hm21** [comment]
Thank you for reporting that issue. I’ve just released version `6.1.3`, which should resolve it. This update ensures that the context menu will close when the user presses the Escape key.
