### ISSUE TITLE
[Bug]: Custom AppBar and BottomBar display wrong position of widget when drag and drop

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#265]
### Package Version

6.1.3

### Flutter Version

3.24.5

### Platforms

Android, iOS, Web

### How to reproduce?

1. Click on ```Custom AppBar and BottomBar```
2. Click on ```Text``` BottomBar menu item
3. Input anything you want such as ```hello```
4. Drag and drop text widget just created on step 3 and see position of widget. 

P/S: This issue only happen in Custom AppBar and BottomBar. I tested with default editor its working.

https://github.com/user-attachments/assets/f9c95db6-d327-43ac-8b30-63d57d2ade7f

**Comment by hm21** [comment]
Thank you for reporting this issue. You are correct that the example “Custom AppBar and BottomBar” still uses the older code version. However, starting with version [5.4.0](https://github.com/hm21/pro_image_editor/blob/stable/CHANGELOG.md#540), I updated the toolbars to no longer hide by default. If you still wish to hide the toolbars during interactions, you can enable this behavior by setting `hideToolbarOnInteraction` to `true` in the `layerInteraction` settings.
