### ISSUE TITLE
[Feature request] Ability to zoom out

### ISSUE THREAD

**Issue by barchinvictor** [hm21/pro_image_editor#266]
### Platforms

Web

### Description

Thank you for this awesome package ❤️ 

Currently editorIsZoomable allows you to zoom in on the canvas. But you can't zoom out because the canvas stretches to the full height of the screen. I'd like to be able to zoom out like many editors do.

Thanks in advance

**Comment by hm21** [comment]
Thank you for your feature request. 

The `editorMinScale` option already allows scaling out, but I realized I had omitted the `boundaryMargin` property from the `InteractiveViewer`, which is necessary for proper functionality. However, I just released version `6.1.4`, which should resolve the issue. You can also refer to this [example](https://github.com/hm21/pro_image_editor/blob/1858aac8f0a37ad186bb2f8a0002540376ed943f/example/lib/pages/zoom_move_editor_example.dart#L68-L79) for guidance on how to configure all the settings for zooming in and out.

**Comment by barchinvictor** [comment]
@hm21 Thanks for the update!

Today I found a small bug. If you enlarge the canvas, the layer scaling does not work correctly. More clearly in the video https://www.youtube.com/watch?v=FmnAFqyzGec

**Comment by hm21** [comment]
Thank you for sharing the video that demonstrates the issue. I will address it as soon as I have time.

**Comment by barchinvictor** [comment]
@hm21 Hi! Any ideas on how to fix this? I'm trying to do it myself, but it doesn't work((

**Comment by hm21** [comment]
@barchinvictor I’m sorry, but I currently don’t have a solution. If you’d like to try finding one yourself, you’ll need to update the calculation [here](https://github.com/hm21/pro_image_editor/blob/8a0dcd76ceaa11fc3e43cac8f065ebc0cdff5176/lib/modules/main_editor/utils/layer_interaction_manager.dart#L185-L186). I’m not sure if it’s required, but it might be necessary to read the transformations from the `InteractiveViewer`, which is wrapped inside the [ExtendedInteractiveViewer](https://github.com/hm21/pro_image_editor/blob/stable/lib/widgets/extended/extended_interactive_viewer.dart).
