### ISSUE TITLE
[Bug]: Layers don't scale properly on different screen sizes

### ISSUE THREAD

**Issue by saif-ellafi** [hm21/pro_image_editor#272]
### Package Version

6.1.3

### Flutter Version

3.24.5

### Platforms

Android, iOS, Web, Windows, macOS, Linux

### How to reproduce?

Go to the demo website and click the "Import and Export State History" demo. pay attention to the layer sizes (emoji, text, etc.)

Now exit the demo, and shrink your browser size to a much smaller window.

The layers, emoji and text are equally bigger as before, and did not scale down with the image.

I tried to fix this here but so far failed: https://github.com/hm21/pro_image_editor/pull/271

Will keep digging in the meantime.

![image](https://github.com/user-attachments/assets/f94dca3b-ada3-491a-8908-e86bd2346d3d)
![image](https://github.com/user-attachments/assets/1e913dbe-0203-417a-b0dc-e1bec323f484)

**Comment by saif-ellafi** [comment]
Tried to fix it but failed, could be in the direction of it though: https://github.com/hm21/pro_image_editor/pull/271

**Comment by saif-ellafi** [comment]
I am glad I could fix it here: https://github.com/hm21/pro_image_editor/pull/273

**Comment by hm21** [comment]
Resolved in PR #273
