### ISSUE TITLE
stickers should can be selected  and drag to rotate

### ISSUE THREAD

**Issue by luyongfugx** [hm21/pro_image_editor#28]
### Platforms

Android, iOS

### Description

stickers should can be selected  and drag to rotate, when click to a sticker or text or anything, it should be seen selected (may be have a border), and can drag or rotate

### Why

it is very common and important to a image editor

**Comment by hm21** [comment]
I just released version `2.7.0` which now supports selecting a layer when you tap/click on it. By default, the layer selection is only enabled on desktop devices, but in the configs like in the example below you can enable it for mobile devices too. When the layer selection is disabled, I follow the interaction style of `WhatsApp` and when the layer selection is enabled, it looks a bit like the selection style in `Line`. Of course, it's possible to change all styles and also the border style can be changed between `solid`, `dashed` and `dotted`. Please tell me if you encounter any issues.

```dart
ProImageEditor.network(
   'https://picsum.photos/id/230/2000',
   key: editorKey,
   onImageEditingComplete: onImageEditingComplete,
   onCloseEditor: onCloseEditor,
   configs: const ProImageEditorConfigs(
        layerInteraction: LayerInteraction(
          /// Choose between `auto`, `enabled` and `disabled`.
          /// 
          /// Mode `auto`:
          /// Automatically determines if the layer is selectable based on the device type.
          /// If the device is a desktop-device, the layer is selectable; otherwise, the layer is not selectable.
          selectable: LayerInteractionSelectable.enabled,
        ),
        imageEditorTheme: ImageEditorTheme(
          layerInteraction: ThemeLayerInteraction(
            buttonRadius: 10,
            strokeWidth: 1.2,
            borderElementWidth: 7,
            borderElementSpace: 5,
            borderColor: Colors.blue,
            removeCursor: SystemMouseCursors.click,
            rotateScaleCursor: SystemMouseCursors.click,
            editCursor: SystemMouseCursors.click,
            hoverCursor: SystemMouseCursors.move,
            borderStyle: LayerInteractionBorderStyle.solid,
            showTooltips: false,
          ),
        ),
        icons: ImageEditorIcons(
          layerInteraction: IconsLayerInteraction(
            remove: Icons.clear,
            edit: Icons.edit_outlined,
            rotateScale: Icons.sync,
          ),
        ),
        i18n: I18n(
          layerInteraction: I18nLayerInteraction(
            remove: 'Remove',
            edit: 'Edit',
            rotateScale: 'Rotate and Scale',
          ),
        ),
      ),
    );
```

**Comment by thanglq1** [comment]
Hi @hm21 . Thanks for your plugin. I really like it. Just want to ask you do we have an option to hide 'remove area' because I saw you just added feature remove emoji/sticker layer.
![remove_area](https://github.com/hm21/pro_image_editor/assets/26729342/a415f2dd-730f-45aa-a9a6-8213ebbab30c)

**Comment by hm21** [comment]
Hi @thanglq1 

Yes, it's possible just override in the `configs` inside `customWidgets` the option `removeLayer` with `SizedBox.shrink()` like below.

```dart
ProImageEditor.asset(
      'assets/demo.png',
      configs: const ProImageEditorConfigs(
        customWidgets: ImageEditorCustomWidgets(
          removeLayer: SizedBox.shrink(),
        ),
      ),
 )
```

**Comment by thanglq1** [comment]
Thank you so much @hm21
