### ISSUE TITLE
[bug] Unable to load asset 'path to file'

### ISSUE THREAD

**Issue by tiltmaster** [hm21/pro_image_editor#3]
**Describe the bug**
Unable to load asset error with the following example: 

```
void _openEditor(path) async {
    File file = File(path);
    bool fileExists = await file.exists();
    if (fileExists) {
      print('File exists at: $path');
    } else {
      print('File does not exist at: $path');
    }
    imagePath = path;
    if (!context.mounted) return;
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ProImageEditor.asset(
          path,
          onImageEditingComplete: (byte) async {
            Directory appDocDir = await getApplicationDocumentsDirectory();
            File file = File('${appDocDir.path}/${DateTime.now().millisecondsSinceEpoch}.jpg');
            await file.writeAsBytes(byte);
            if (!context.mounted) return;
            imagePath = file.path;
            Navigator.pop(context);
          },
        ),
      ),
    );
  }
```
Knowing that passing and checking if fileExists returns true.

**Steps to Reproduce**
1. Take Picture
2. Call Editor Function
3. Error appears with exception in editor.

**Expected Behavior**
To load the image as expected.

**Comment by hm21** [comment]
Thanks for your bug report.

I noticed that you attempted to open a file using `ProImageEditor.asset`. To successfully open a file, you should utilize `ProImageEditor.file`. Below is an example demonstrating how to integrate it with your code. Please note that `ProImageEditor.asset` is exclusively designed for opening assets explicitly declared in your pubspec.yaml file.

```dart
void _openEditor(path) async {
    File file = File(path);
    bool fileExists = await file.exists();
    if (fileExists) {
      print('File exists at: $path');
    } else {
      print('File does not exist at: $path');
    }
    imagePath = path;
    if (!context.mounted) return;
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ProImageEditor.file(
          file,
          onImageEditingComplete: (byte) async {
            Directory appDocDir = await getApplicationDocumentsDirectory();
            File file = File('${appDocDir.path}/${DateTime.now().millisecondsSinceEpoch}.jpg');
            await file.writeAsBytes(byte);
            if (!context.mounted) return;
            imagePath = file.path;
            Navigator.pop(context);
          },
        ),
      ),
    );
  }
```

**Comment by tiltmaster** [comment]
> Thanks for your bug report.
> 
> I noticed that you attempted to open a file using `ProImageEditor.asset`. To successfully open a file, you should utilize `ProImageEditor.file`. Below is an example demonstrating how to integrate it with your code. Please note that `ProImageEditor.asset` is exclusively designed for opening assets explicitly declared in your pubspec.yaml file.
> 
> ```dart
> void _openEditor(path) async {
>     File file = File(path);
>     bool fileExists = await file.exists();
>     if (fileExists) {
>       print('File exists at: $path');
>     } else {
>       print('File does not exist at: $path');
>     }
>     imagePath = path;
>     if (!context.mounted) return;
>     await Navigator.push(
>       context,
>       MaterialPageRoute(
>         builder: (context) => ProImageEditor.file(
>           file,
>           onImageEditingComplete: (byte) async {
>             Directory appDocDir = await getApplicationDocumentsDirectory();
>             File file = File('${appDocDir.path}/${DateTime.now().millisecondsSinceEpoch}.jpg');
>             await file.writeAsBytes(byte);
>             if (!context.mounted) return;
>             imagePath = file.path;
>             Navigator.pop(context);
>           },
>         ),
>       ),
>     );
>   }
> ```
Thank you for this feedback, i may have been a bit confused between asset and path, but using asset as such instead of .file actually was returning the above error, i managed to go around this by doing the below:
```
void _openEditor(path) async {
    final pathOfXFile = await path.readAsBytes();
    if (!context.mounted) return;
    await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (context) => ProImageEditor.memory(
          pathOfXFile,
          onImageEditingComplete: (byte) async {
            Directory appDocDir = await getApplicationDocumentsDirectory();
            File file = File('${appDocDir.path}/${DateTime.now().millisecondsSinceEpoch}.jpg');
            await file.writeAsBytes(byte);
            if (!context.mounted) return;
            imagePath = file.path;
            Navigator.pop(context);
          },
        ),
      ),
    );
  }
```
which works like a charm for both picked images from image_picker & captured images.
