### ISSUE TITLE
Change the color of the appBar and bottom nav bar in main screen [Feature request] 

### ISSUE THREAD

**Issue by mahdiyarz** [hm21/pro_image_editor#31]
### Platforms

Android, iOS, Web

### Description

This package is very useful and thank you for the great job.
I've been checked all documents and there was some features that doesn't exist now! e.g. WhatsApp mode and change the color of the appBar (`appBarBackgroundColor` in `imageEditorTheme`) and bottom nav bar (`bottomBarBackgroundColor` in `imageEditorTheme`) in main edit screen. It would be great to implement these feature again.

**Comment by thanglq1** [comment]
Hi @mahdiyarz. You can change it in ProEditorConfig something like this
```
configs: ProImageEditorConfigs(
                          imageEditorTheme: ImageEditorTheme(
                            appBarBackgroundColor: Colors.red,
                          ),
)
```

**Comment by mahdiyarz** [comment]
> appBarBackgroundColor: Colors.red,

Hi @thanglq1,
unfortunately The named parameter `appBarBackgroundColor` isn't defined in `ImageEditorTheme`. what's your package version?
mine is 2.4.3

**Comment by thanglq1** [comment]
I'm using 2.7.0. You should update latest version. Now its 2.7.1

**Comment by mahdiyarz** [comment]
Many thanks to you.
