### ISSUE TITLE
[Bug]: Close editor is not working properly

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#32]
### Package Version

2.7.0

### Flutter Version

3.19.6

### Platforms

Android, iOS

### How to reproduce?

After clicking the 'Ok' button on the 'Close Image Editor' popup, it doesn't navigate back. it still displays the 'Result' screen with below code. In your sample code, you called ```Navigator.pop(context)``` method to exit 'MainEditor' screen but I want the user to be able to edit when they return from the 'Result' screen then I comment out ```Navigator.pop(context);``` in ```onImageEditingComplete()``` method.
Better we should have an option for user can custom ```closeWarning()``` method (Popup called on ```PopScope```) then they can handle their logic.

```
  Future<void> onImageEditingComplete(bytes) async {
    editedBytes = bytes;
    // I want the user to be able to edit when they return from the 'Result' screen. That's why I didn't call the Navigator.pop(context) method.
    // Navigator.pop(context);
  }

  void onCloseEditor() {
    if (editedBytes != null) {
      Navigator.push(
        context,
        MaterialPageRoute(
          builder: (context) {
            return PreviewImgPage(imgBytes: editedBytes!);
          },
        ),
      );
    } else {
      Navigator.pop(context);
    }
  }
```

1. Open Editor screen and edit something such as add text/emoji
2. On 'Main Editor' screen, click on 'Done' button. It will be go to 'Result' screen
3. On 'Result' screen, click on 'Back' button on appbar
4. On 'Main Editor' screen, click on 'Cancel/Close' button
5. On 'Close Image Editor' popup, click on 'OK' button.

Actually: Display 'Result' screen
Expected: Pop back, not display the 'Result' screen

**Comment by hm21** [comment]
I'm not sure if I understand you correctly, but your goal is to directly close the editor without showing the result screen, right? You can edit like below that no `preview` screen is shown. The preview screen I just added for the example, but in real applications I think it's useless too.

```dart
ProImageEditor.memory(
        _transparentBytes,
        key: editorKey,
        onImageEditingComplete: (bytes) async {
          /// Handle the bytes => maybe upload to your server
          print(bytes.length);
          Navigator.pop(context, bytes);
        },
        // Not required in this case => onCloseEditor: onCloseEditor,
)
```

**Comment by thanglq1** [comment]
> I'm not sure if I understand you correctly, but your goal is to directly close the editor without showing the result screen, right? You can edit like below that no `preview` screen is shown. The preview screen I just added for the example, but in real applications I think it's useless too.
> 
> ```dart
> ProImageEditor.memory(
>         _transparentBytes,
>         key: editorKey,
>         onImageEditingComplete: (bytes) async {
>           /// Handle the bytes => maybe upload to your server
>           print(bytes.length);
>           Navigator.pop(context, bytes);
>         },
>         // Not required in this case => onCloseEditor: onCloseEditor,
> )
> ```

Thanks for your suggestion. No need ```onCloseEditor```. Could you expose a property to customize the 'closeWarning' popup dialog?

**Comment by hm21** [comment]
Sure, I added the ability to create a complete custom solution for `closeWarning` like you wanted in version `2.7.2`. Below is an example of how to do it:

```dart
 configs: ProImageEditorConfigs(
    customWidgets: ImageEditorCustomWidgets(
      closeWarningDialog: () async {
        return await showDialog<bool>(
              context: context,
              builder: (BuildContext context) => AlertDialog(
                title: const Text('Close?'),
                content: const Text('Are you sure you want to close the Image Editor? Your changes will not be saved.'),
                actions: <Widget>[
                  TextButton(
                    onPressed: () => Navigator.pop(context, false),
                    child: const Text('Cancel'),
                  ),
                  TextButton(
                    onPressed: () => Navigator.pop(context, true),
                    child: const Text('OK'),
                  ),
                ],
              ),
            ) ??
            false;
      },
    ),
),
```

**Comment by thanglq1** [comment]
Many thanks! @hm21
