### ISSUE TITLE
[Bug]: Example doesn't run on Linux

### ISSUE THREAD

**Issue by sgehrman** [hm21/pro_image_editor#34]
### Package Version

22

### Flutter Version

22

### Platforms

Linux

### How to reproduce?

run exampled

### Logs (optional)

```sh
Launching lib/main.dart on Linux in debug mode...
CMake Error at CMakeLists.txt:51 (add_subdirectory):
  The source directory

    /home/steve/expr/pro_image_editor/example/linux/flutter

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:114 (install):
  install FILES given directory "" to install.


CMake Error at CMakeLists.txt:117 (install):
  install FILES given directory "" to install.


Error: Unable to generate build files

Exited (1).
```

### Example code (optional)

```Dart
sdfdddd
```

### Device Model (optional)

linux

**Comment by sgehrman** [comment]
I fixed it.  Delete the linux folder and create it fresh.  $ flutter create .

**Comment by hm21** [comment]
Thanks Steve for reporting this issue, I just fixed it and the example should now work directly without `flutter create .` on linux.
