### ISSUE TITLE
[Bug]: Loader doesn't stop after apply edit

### ISSUE THREAD

**Issue by UmangPandav** [hm21/pro_image_editor#39]
### Package Version

2.7.3

### Flutter Version

3.19.6

### Platforms

Android

### How to reproduce?

I found this issue after applying changes

### Example code (optional)

```Dart
mixin ExampleHelperState<T extends StatefulWidget> on State<T> {

  Uint8List? editedBytes;

  Future<void> onImageEditingComplete(bytes) async {
    editedBytes = bytes;
    pop(context);
  }

  Future<void> onCloseEditor() async {
    if (editedBytes != null) {
      navigationPush(context: context, to: ImageEditPage(imageByte: editedBytes!)).whenComplete(() {
        editedBytes = null;
      });
    } else {
      pop(context);
    }
  }
}

ProImageEditor.memory(
      widget.imageByte!,
      onImageEditingComplete: onImageEditingComplete,
      onCloseEditor: onCloseEditor,
      allowCompleteWithEmptyEditing: true,
      configs: proImageEditorConfigs(context)
    )
```

**Comment by hm21** [comment]
Thank you for reporting this issue. 

Currently, I can't reproduce this issue on Android devices. Can you test if it happens only on specific devices or on multiple different devices? Please also let me know on which specific devices the issue is happening. 

I see you are using `pop(context)` which seems to me that you are using an external package, or you have written a global function. Can you share with me the name of the package or the code of this global function?

**Comment by UmangPandav** [comment]
Changes are being applied show continuously, even after changes applied

**Comment by UmangPandav** [comment]
pop(context). it's not a package. it just used as Navigator.pop(context) in short form

**Comment by hm21** [comment]
Can you try the code from the example and check if it's work?
On which device happen the issue (as example Galaxy S10)?

**Comment by UmangPandav** [comment]
how to change bottom list icons and text color in editor like paint, text and all

**Comment by hm21** [comment]
You switch from an issue report to a question in the same post. I would like it if you create a new “issue” with the “question” template or start a new “discussion” [here](https://github.com/hm21/pro_image_editor/discussions). The community and I will guide you there, but it makes no sense to mix issue and question in the same post.

The fact that you didn't respond to my answer [here](https://github.com/hm21/pro_image_editor/issues/39#issuecomment-2100884823) makes me think that you found the problem in your own code, right? In that case, I will close this issue.

**Comment by UmangPandav** [comment]
It's not a bug. There is a bug with my code, and this issue shows up because of the overlapping of two packages.
