### ISSUE TITLE
Add a Custom Bottom Bar for the TextEditor When Using Custom Text Styles

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#40]
### Platforms

Android, iOS

### Description

Hi @hm21. If we can change the bottom bar in the painting editor, I think users should be able to customize the bottom bar for the text editor when they use custom text styles (Google fonts).

**Comment by hm21** [comment]
You are right, I also think it makes sense that users can add a custom bottomBar in the text editor. I have released version `2.7.6` which includes this future.
