### ISSUE TITLE
Border layer should be removed after editing is done

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#42]
### Platforms

Android, iOS

### Description

Hi @hm21. For better UX we should remove border layer after editing is done

![z5426051784483_0d3472fa38e8334b9930c71f14073207](https://github.com/hm21/pro_image_editor/assets/26729342/4672652a-f4d7-4c0f-ad31-3eeabfb6e710)

**Comment by hm21** [comment]
You are right, it should deselect all layers when finished editing. I just released version `2.7.7` which resolves this issue.
