### ISSUE TITLE
Add an option to allow users to enable showing the layer immediately after adding a sticker

### ISSUE THREAD

**Issue by thanglq1** [hm21/pro_image_editor#44]
### Platforms

Android, iOS

### Description

Hi @hm21. Please help add an option to allow users to enable showing the layer immediately after adding a sticker or emoji.

**Comment by hm21** [comment]
With “layer” you mean the selection border around the “layer” with the interaction buttons, right? 
If yes, I added this feature in version `2.7.8`. You can enable/ disable this option like below:

```dart
 configs: const ProImageEditorConfigs(
        layerInteraction: LayerInteraction(
          selectable: LayerInteractionSelectable.enabled,
          initialSelected: true, /// new option
        ),
),
```

**Comment by thanglq1** [comment]
> With “layer” you mean the selection border around the “layer” with the interaction buttons, right? If yes, I added this feature in version `2.7.8`. You can enable/ disable this option like below:
> 
> ```dart
>  configs: const ProImageEditorConfigs(
>         layerInteraction: LayerInteraction(
>           selectable: LayerInteractionSelectable.enabled,
>           initialSelected: true, /// new option
>         ),
> ),
> ```

Yes, thank you. I have just checked. Its working now. Could you help add more option to custom layer such as border width, border color, close button, rotation button.

**Comment by hm21** [comment]
Actually, I already added options to configure the editor like below:
```dart
      configs: const ProImageEditorConfigs(
        layerInteraction: LayerInteraction(
          selectable: LayerInteractionSelectable.enabled,
          initialSelected: true,
        ),
        imageEditorTheme: ImageEditorTheme(
          layerInteraction: ThemeLayerInteraction(
            buttonRadius: 10,
            strokeWidth: 1.2,
            borderElementWidth: 7,
            borderElementSpace: 5,
            borderColor: Colors.blue,
            removeCursor: SystemMouseCursors.click,
            rotateScaleCursor: SystemMouseCursors.click,
            editCursor: SystemMouseCursors.click,
            hoverCursor: SystemMouseCursors.move,
            borderStyle: LayerInteractionBorderStyle.solid,
            showTooltips: false,
          ),
        ),
        icons: ImageEditorIcons(
          layerInteraction: IconsLayerInteraction(
            remove: Icons.clear,
            edit: Icons.edit_outlined,
            rotateScale: Icons.sync,
          ),
        ),
        i18n: I18n(
          layerInteraction: I18nLayerInteraction(
            remove: 'Remove',
            edit: 'Edit',
            rotateScale: 'Rotate and Scale',
          ),
        ),
      ),
```

**Comment by thanglq1** [comment]
Yes, but can not custom close and rotate button.

**Comment by hm21** [comment]
Do you want to change the background and icon color of the button or create a complete custom button?

**Comment by thanglq1** [comment]
Currently I just want to change background and icon color but I think we should support create a complete custom as well.

**Comment by hm21** [comment]
Okay, after I release the new crop-rotate-editor I will add some options to replace and style the buttons or if you have time, you can create a pull request with the required options I will merge it then.

**Comment by thanglq1** [comment]
Sorry, for Flutter, I'm a newbie. I can't create a pull request
