### ISSUE TITLE
[Feature request] Open editor on a specific page

### ISSUE THREAD

**Issue by pitriq** [hm21/pro_image_editor#46]
### Platforms

Android, iOS

### Description

Hey there, great package!

I would like to have the editor start on a specific page (i.e in the painting editor), but I haven't found a way to do so. Would it be possible to have a config like:

```dart
paintEditorConfigs: PaintEditorConfigs(
  initialPage: true,
),
```

Or to expose a controller so that I can explicitly trigger the page change as soon as I open the editor?

### Why

Our users use the painting feature way more than the other sorts of edition, so it would be easier for them if we had the editor open in that particular mode

**Comment by hm21** [comment]
Thanks for your feature request.

Actually, it's possible to add this feature that it will directly open an “initial page” but in my opinion, in most cases this will confuse the users. The point is when you open the editor, and it will directly add another page, it can confuse the user when the user taps on the “back button” which shows him another page (the main editor) which the user didn't see before.

Anyway, if you have this special case where it's nessacary, you can do it like below. I haven't tested the code in the stable branch, just with the code from the dev branch, but it should still work. Please let me know if it makes a problem.

```dart
final _editorKey = GlobalKey<ProImageEditorState>();

@override
Widget build(BuildContext context) {
  return ListTile(
    onTap: () {
      bool initHelper = false;
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (context) => Builder(builder: (context) {
            if (!initHelper) {
              initHelper = true;
              Future.delayed(const Duration(milliseconds: 1), () {
                _editorKey.currentState!.openPaintingEditor();
              });
            }
            return _buildEditor();
          }),
        ),
      );
    },
    title: const Text('Test'),
    trailing: const Icon(Icons.chevron_right),
  );
}

Widget _buildEditor() {
  return ProImageEditor.asset(
    'assets/demo.png',
    key: _editorKey,
    callbacks: ProImageEditorCallbacks(
      onImageEditingComplete: onImageEditingComplete,
      onCloseEditor: onCloseEditor,
    ),
    configs: const ProImageEditorConfigs(),
  );
}
```
