### ISSUE TITLE
[bug]  Bottom Overflow

### ISSUE THREAD

**Issue by YofarDev** [hm21/pro_image_editor#5]
Hello, I tried the package in an app on my physical device (Samsung Galaxy 10e), and got a bottom overflow warning :

![Screenshot_20240212_153130](https://github.com/hm21/pro_image_editor/assets/51706943/e406559a-9be5-4747-9b50-71e7f8b59ba4)

**Comment by hm21** [comment]
Hi YofarDev,

Thank you for reporting that issue. In my opinion, is the problem from the custom IconButton in the BottomAppBar which is extended from `TextButton`, which seems to add varying padding on different devices. However, I've added fixed padding, which should solve this issue. I tested it on a real Samsung Galaxy S10 (not the S10e), and it appeared fine, but I'm uncertain about the S10e. Please let me know if the issue persists on your S10e.

**Comment by YofarDev** [comment]
Yeah it's fixed! Thanks it was quick.
