### ISSUE TITLE
[Bug]: useColorEmoji doesn't work with new 3.22 web loading method

### ISSUE THREAD

**Issue by sgehrman** [hm21/pro_image_editor#53]
### Package Version

2.7.9

### Flutter Version

3.22

### Platforms

Web

### How to reproduce?

see this:

if you flutter create . it will make an app with the new loading method for web

https://docs.flutter.dev/platform-integration/web/bootstrapping

I tried the useColorEmoji: true in the config, but it didn't work.

**Comment by hm21** [comment]
Yup in my tests it didn't work either. I think flutter has a bug that the new configs part not working. Anyway, you can try the code like in the example from the dev branch [here](https://github.com/hm21/pro_image_editor/blob/dev/example/web/flutter_bootstrap.js), in my case that code works.

**Comment by sgehrman** [comment]
Thanks
