### ISSUE TITLE
[Bug]: Closing dialog that contains image editor without saving first has exception

### ISSUE THREAD

**Issue by sgehrman** [hm21/pro_image_editor#54]
### Package Version

2.7.9

### Flutter Version

3.22

### Platforms

Web

### How to reproduce?

Put image editor in a dialog.  Add an emoji and close the parent dialog without saving first.  Seems the warning dialog about saving unsaved changes doesn't work in this case.

Error: Assertion failed: file:///home/steve/development/flutter/packages/flutter/lib/src/widgets/navigator.dart:4817:12
!_debugLocked
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/widgets/navigator.dart 4817:13                               [_pushEntry]
packages/flutter/src/widgets/navigator.dart 4774:5                                push
packages/flutter/src/material/dialog.dart 1436:63                                 showDialog
packages/flutter/src/material/dialog.dart 1476:14                                 showAdaptiveDialog
packages/pro_image_editor/modules/main_editor/main_editor.dart 1397:13            closeWarning

### Logs (optional)

```sh
Error: Assertion failed: file:///home/steve/development/flutter/packages/flutter/lib/src/widgets/navigator.dart:4817:12
!_debugLocked
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 296:3       throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3        assertFailed
packages/flutter/src/widgets/navigator.dart 4817:13                               [_pushEntry]
packages/flutter/src/widgets/navigator.dart 4774:5                                push
packages/flutter/src/material/dialog.dart 1436:63                                 showDialog
packages/flutter/src/material/dialog.dart 1476:14                                 showAdaptiveDialog
packages/pro_image_editor/modules/main_editor/main_editor.dart 1397:13            closeWarning
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/pro_image_editor/modules/main_editor/main_editor.dart 1389:20            closeWarning
packages/pro_image_editor/modules/main_editor/main_editor.dart 1543:15            <fn>
packages/flutter/src/widgets/routes.dart 1739:30                                  onPopInvoked
packages/flutter/src/widgets/navigator.dart 3112:5                                pop
packages/flutter/src/widgets/navigator.dart 5287:12                               pop
packages/shared_ui/src/dialogs/dialog_base.dart 126:29                            <fn>
packages/flutter/src/material/ink_well.dart 1171:21                               handleTap
packages/flutter/src/gestures/recognizer.dart 344:24                              invokeCallback
packages/flutter/src/gestures/tap.dart 652:11                                     handleTapUp
packages/flutter/src/gestures/tap.dart 309:5                                      [_checkUp]
packages/flutter/src/gestures/tap.dart 242:7                                      handlePrimaryPointer
```

**Comment by hm21** [comment]
Can you create an example for me how I can reproduce it? In my tests, I can't reproduce this error. And does it happen only in a specific browser like Safari or in several web browsers?

**Comment by hm21** [comment]
Closed due to no response from the author.
