### ISSUE TITLE
[Feature request] Can we add ready templates (like predefined text or image on some position

### ISSUE THREAD

**Issue by murat-ti** [hm21/pro_image_editor#65]
### Platforms

Android, iOS, Web, Windows, macOS, Linux

### Description

I think it will be good to have some predefined templates. As, example in Photoshop we have psd format, which we can save as template and then reuse/change/export it. Imagine I have t-shirt with name/surname on top and big sized number in center on back side of t-shirt, like football players wears. And we can load this template change name/surname and number without any other actions. Thank you
![Screenshot_2](https://github.com/hm21/pro_image_editor/assets/33370868/5dc20bdf-4977-4ea2-928f-4bf2fe3e305b)

### Why

It is must to have feature I think and also it will save time to desing.

**Comment by hm21** [comment]
If I understand you correctly, then is that future already included. 
You can take a look at this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/import_export_example.dart) which shows you how to import or export your current state. In the web [demo](https://hm21.github.io/pro_image_editor/) you can scroll to “Import and Export State History” which will show you the example in action.

**Comment by murat-ti** [comment]
Thank you for quick response. Now I see it.
I really apreciate you for your work
