### ISSUE TITLE
[Feature request] More text options (bold, italic, underline, lists)

### ISSUE THREAD

**Issue by adamkoch** [hm21/pro_image_editor#67]
### Platforms

Android, iOS, Web

### Description

It would be great to add more text formatting options, the main ones being:

 - common formatting - bold, italic, underline
 - lists - numbered and and bullets

There are probably more :-)

Thanks!

### Why

Adds more flexibility to the existing text tool which already has sizing and rotate ability (and font changing which is awesome!).

**Comment by hm21** [comment]
Thanks for your feature request.

To do this, you can replace the `AppBar` or `BottomBar` with a custom widget in the configs. You can then access the editor with the global key and use the `setTextStyle` method in the text-editor to update the text style depending on your use case.
As an example, you can call the function like below:
```dart
editorKey.currentState!.textEditor.currentState!.setTextStyle(
      const TextStyle(
        decoration: TextDecoration.lineThrough,
        fontWeight: FontWeight.bold,
        fontStyle: FontStyle.italic,
      ),
    );
```
In this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/custom_appbar_bottombar_example.dart), you can see how to create your own widgets that allow you to interact with the editor in a way that fits your use case exactly.

**Comment by adamkoch** [comment]
Amazing, thank you! Will give it a go.

**Comment by adamkoch** [comment]
Quick follow up. I gave this a go and it works really well for the most part. The way you designed it is very flexible. Underline and italics works without issue.

One minor thing I noticed, the underline style when editing the text has an additional white underline underneath it (usually what you see when there is no Material() parent). Once I exit out of edit mode the string is rendered without the white underline. Not sure if you have any ideas about if that `Text()` may be missing a parent `Material()`?

And the second thing, is that bold style seems to apply fine but does not actually visually change. Not sure if this is related to Material() parent as well or if it's a GoogleFonts issue where it isn't getting the bold versions of the fonts. I will keep digging here but thought you may have an idea.

Screenshots of text underline bit:

![Simulator Screenshot - iPhone 15 Pro - 2024-06-09 at 14 03 35](https://github.com/hm21/pro_image_editor/assets/869261/4f2ae4cc-f9a8-418e-a459-9ad235e0f382)
![Simulator Screenshot - iPhone 15 Pro - 2024-06-09 at 14 03 35 copy](https://github.com/hm21/pro_image_editor/assets/869261/51d6e848-f07b-4c08-b289-0d45881aec75)
