### ISSUE TITLE
Feature Request: Landscape support

### ISSUE THREAD

**Issue by ynnob** [hm21/pro_image_editor#7]
**Is your feature request related to a problem? Please describe.**
Currently landsscape mode is not supported and the widget will always fallback to portrait mode

**Describe the solution you'd like**
For tablet users that mainly use our app in landscape mode this change in orientation can be confusing and in addition to that we navigate from differently oriented dynamic screens to pro_image_editor and that makes it kind of tricky to restore the orientation of the previous screen correctly.

**Describe alternatives you've considered**
I guess one way would be to wrap your widget into a rotation widget but i don't think this is a viable solution to the problem

**Additional context**
At the moment i don't really see a problem with allowing other device orientations. Only the implemented color slider might overflow on some devices. I want the user to decide in which orientation he  uses the phone and maybe the color slider should be rotated horizontally in landscape mode. Most phone users will not use landscape mode in the app anyway or manually lock their screens to their prefrered orientation.

What are your thoughts on that?

**Comment by hm21** [comment]
Thanks for your Feature Request.
I've updated and uploaded version `2.4.2`, which now supports all device orientations. Additionally, the color slider will automatically resize if the device screen is too small. However, I believe it's unlikely that users will rotate their small smartphones to edit images, so this should not be a significant concern. While I haven't extensively tested it on tablets, please inform me if there is any issue.
