### ISSUE TITLE
[Bug]: Navigator.pop() does not seem to return data to the caller

### ISSUE THREAD

**Issue by adamkoch** [hm21/pro_image_editor#72]
### Package Version

3.0.4

### Flutter Version

3.22.2

### Platforms

Android, iOS

### How to reproduce?

Not sure if I'm doing something wrong, but I can't seem to get Navigator.pop() to return the value back to the screen that called Navigator.push().

Here is a simple example that doesn't work for me, returning a string instead of the bytes. The final log always has result=null.

Any ideas?

```
    final result = await Navigator.push(
      context,
      MaterialPageRoute(
        builder: (_) => ProImageEditor.network(
          url,
          callbacks:
              ProImageEditorCallbacks(onImageEditingComplete: (bytes) async {
            // Navigator.of(context).pop(bytes);
            Navigator.of(context).pop('testing');
          }),
        ),
        fullscreenDialog: true,
      ),
    );
    log('result = $result / ${result != null}');
```

**Comment by hm21** [comment]
Yes, it's not possible because the editor also has to call `Navigator.pop(context)` internally to close the “loading-dialog”, so you never get any data back, which is why there are so many callbacks.
However, if you want to handle the bytes outside the callback, you can do it like this:

```dart
Uint8List? result;
await Navigator.push(
  context,
  MaterialPageRoute(
    builder: (_) => ProImageEditor.network(
      url,
      callbacks:
          ProImageEditorCallbacks(onImageEditingComplete: (bytes) async {
        result = bytes;
      }),
    ),
    fullscreenDialog: true,
  ),
);
log('result = ${result?.length}');
```

**Comment by adamkoch** [comment]
Ahh thanks! I thought I was doing something wrong in my code. Will give your workaround a go, thanks 👍
