### ISSUE TITLE
[Bug]: web_worker.dart file causing errors.  why is it included ?

### ISSUE THREAD

**Issue by sgehrman** [hm21/pro_image_editor#73]
### Package Version

3.0.5

### Flutter Version

3.22

### Platforms

Web

### How to reproduce?

build it

### Logs (optional)

```sh
xx
```

### Example code (optional)

```Dart
xx
```

**Comment by sgehrman** [comment]
![Screenshot from 2024-06-09 16-54-00](https://github.com/hm21/pro_image_editor/assets/287137/6776001f-2518-4651-a7a4-d220cfb12b0b)

**Comment by hm21** [comment]
You're right, `web_worker.dart` is not needed on the web build because I already converted it to `web_worker.dart.js`. However, I have released version `3.0.6` where this file is excluded.
