### ISSUE TITLE
Feature Request: Multiple images 

### ISSUE THREAD

**Issue by Aniketkhote** [hm21/pro_image_editor#9]
Option to add multiple images to create album.

**Comment by hm21** [comment]
With the sticker editor, it is already possible to add multiple images to the editor. But I think you want that there is no fixed background image and only “sticker images” which you can move around, right? In this case, It will need some time to change the code. 

The following tasks are required.

- [ ] New configuration option which supports no background image. This option should convert the initialization image to a sticker and use a transparent image for the background image that the full editor area is available.
- [ ] Crop function that removes the transparent area around the images when saving the “editor image”.
- [ ] New configuration option that allows the Filter Editor to display stickers.
- [ ] Each sticker must be wrapped inside the filter widget (stickers should have an option which apply the filter or not).
- [ ] Editable layers and new images (stickers) should directly be added to lower layer levels than layers such as “Text” or “Paint”.

**Comment by Aniketkhote** [comment]
Would love to see an option to select multiple images from the gallery, similar to Instagram stories. Would that be possible?

**Comment by hm21** [comment]
Yes, after I update the code it will be possible. I'm not sure if I will add a direct option that will access a package like `image_picker` or if I will just give an option that allows the user to insert the images but with the freedom to use the image picker package they like. However, I will update the readme file with an example then.

**Comment by Aniketkhote** [comment]
When do you anticipate the feature will be completed? Also, I'm interested in customizing the look of the widget for my production app to allow users to modify images similar to the options available in Instagram stories. Is this possible?

**Comment by hm21** [comment]
It's hard to say when I'll implement this future, because I don't need this future in my personal projects right now, so I'm just programming this for fun and prestige. But maybe at the end of this month if I find the time.

The editor is very configurable as you can see [here](https://github.com/hm21/pro_image_editor?tab=readme-ov-file#highly-configurable). You can change any color, icon, text and even replace entire widgets. In this future request [https://github.com/hm21/pro_image_editor/issues/1](https://github.com/hm21/pro_image_editor/issues/1) I also posted an example of how to change the appbar and bottombar. 
Actually, I also had the plan to implement default design modes like WhatsApp, Instagram, and Facebook when the package has more than 100 likes because then I know many people use and like it.

If you require this future as fast as possible, I recommend you fork this package and add your own solution. In this case, you can also easily edit and design everything the way you need it.

**Comment by JayeshMardiya** [comment]
@hm21
Is there any branch or PR to edit multiple images like WhatsApp  or Instagram?

**Comment by hm21** [comment]
@JayeshMardiya 
There is no PR or Branch, but the image editor already supports editing multiple images. If you want to edit multiple images in the same editor as on Instagram, you can take a look at this [example](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/movable_background_image.dart) where you can add multiple images.
If you want to do it like in WhatsApp where each image is edited separately, you can create multiple editor instances and swipe between them. The sample code for the WhatsApp design can be seen [here](https://github.com/hm21/pro_image_editor/blob/stable/example/lib/pages/design_examples/whatsapp_example.dart).

**Comment by JayeshMardiya** [comment]
@hm21 Is it possible to edit video and image both together like WhatsApp?

**Comment by hm21** [comment]
@JayeshMardiya, currently, the `pro_image_editor` does not support video editing. However, you can still achieve this by using the `video_player` package in combination with a page slider, where you wrap both the `pro_image_editor` and `video_player` inside.

If this approach seems too complex or time-consuming, I came across this [package](https://pub.dev/packages/flutter_story_editor), which appears to offer exactly what you need. Please note that I haven't personally tried this package, so I can't speak to its quality, but it does claim to support both image and video editing with a WhatsApp-style interface.

**Comment by JayeshMardiya** [comment]
@hm21  I like `pro_image_editor`, so I don't want to use any other package, Is there any alternative way that I don't need to replace `pro_image_editor` with other?

**Comment by hm21** [comment]
In this case you need to wrap the `pro_image_editor` inside a PageView where you create your own logic to switch between the image and video editors. I have a plan to create an example for this in the future, but currently I'm a bit busy with work, so I can't create it right now.

**Comment by JayeshMardiya** [comment]
@hm21 Thanks for prompt reply, Once you create example, please inform here.
